{10}{}{Герой мужчина}
{20}{}{Герой женщина}
{30}{}{Житель}
{40}{}{Житель}
{50}{}{Рад-скорпион}
{51}{}{Маленький мутировавший скорпион.}
{60}{}{Рад-скорпион}
{61}{}{Мутировавший скорпион.}
{70}{}{Коготь Смерти}
{71}{}{Молодой Коготь Смерти.}
{80}{}{Коготь Смерти}
{81}{}{Молодой Коготь Смерти.}
{90}{}{Собака}
{91}{}{Собака, вероятно смешанной породы.}
{100}{}{Брамин}
{101}{}{Двуглавая корова-мутант.}
{110}{}{Крыса}
{111}{}{Типичная большая крыса.}
{120}{}{Мантис}
{121}{}{Мутировавший богомол.}
{130}{}{Старик}
{140}{}{Хакунин}
{150}{}{Минок}
{160}{}{Спороносное растение}
{161}{}{Плотоядное растение.}
{170}{}{Слабый раб}
{180}{}{Красивый Раб}
{190}{}{Здоровый Раб}
{200}{}{Здоровый Раб}
{210}{}{Сильный Раб}
{220}{}{Сильный Раб}
{230}{}{Раб-боец}
{240}{}{Раб-боец}
{250}{}{Умный Раб}
{260}{}{Умный Раб}
{270}{}{Общий Раб}
{280}{}{Общий Раб}
{290}{}{Анна}
{300}{}{Крепкий бандит}
{310}{}{Крепкий бандит}
{320}{}{Бандит-Громила}
{330}{}{Бандит-Громила}
{340}{}{Ловкий Бандит}
{350}{}{Ловкий Бандит}
{360}{}{Бандит с пушкой}
{370}{}{Бандит с пушкой}
{380}{}{Бандит с большой пушкой}
{390}{}{Бандит с большой пушкой}
{400}{}{Крепкий Страж}
{410}{}{Крепкий Страж}
{420}{}{Охранник-Крушила}
{430}{}{Охранник-Крушила}
{440}{}{Ловкий Охранник}
{450}{}{Ловкий Охранник}
{460}{}{Вооруженный Охранник}
{470}{}{Вооруженный Охранник}
{480}{}{Охранник с большой пушкой}
{490}{}{Охранник с большой пушкой}
{500}{}{Сирота (мужчина)}
{510}{}{Сирота (женщина)}
{520}{}{Ребенок (мужчина)}
{530}{}{Ребенок (женщина)}
{540}{}{Неудачник}
{550}{}{Неудачник}
{560}{}{Плохой торговец}
{570}{}{Плохой торговец}
{580}{}{Обычный торговец}
{590}{}{Обычный торговец}
{600}{}{Торговец-мастер}
{610}{}{Торговец-мастер}
{620}{}{Вик}
{630}{}{Слабый крестьянин}
{640}{}{Слабый крестьянин}
{650}{}{Обычный крестьянин}
{660}{}{Обычный крестьянин}
{670}{}{Сильный крестьянин}
{680}{}{Сильный крестьянин}
{690}{}{Слабый охранник ближнего боя}
{700}{}{Слабый охранник ближнего боя}
{710}{}{Слабый вооруженный охранник}
{720}{}{Слабый вооруженный охранник}
{730}{}{Робот-ремонтник}
{740}{}{Робот-ремонтник мк II}
{750}{}{Робомозг}
{760}{}{Летающий робоглаз}
{770}{}{Охранный робот}
{780}{}{Охранный робот мк2 II}
{790}{}{Робомозг}
{800}{}{Маленький Геккон}
{810}{}{Мощный маленький Геккон}
{820}{}{Дикий пес}
{821}{}{Смешанная порода диких собак.}
{830}{}{Золотой Геккон}
{840}{}{Коготь Смерти}
{850}{}{Рассадник Когтей Смерти}
{860}{}{Мощный золотой геккон}
{870}{}{Линетт}
{880}{}{Доктор Трой}
{890}{}{Джон Кэсседи}
{900}{}{Грегори}
{910}{}{Гражданин (женщина)}
{920}{}{Гражданин (мужчина)}
{930}{}{Гражданин высшего класса (F)}
{940}{}{Гражданин высшего класса (M)}
{950}{}{Охотник}
{960}{}{Охотник}
{970}{}{Сулик}
{980}{}{Майда Бакнер}
{990}{}{Торр}
{1000}{}{Лумпи}
{1010}{}{Reactor Glowing One}
{1020}{}{Гуль реактора}
{1030}{}{Охранник реактора}
{1040}{}{Зомак}
{1050}{}{Скитер}
{1060}{}{Мозг}
{1070}{}{Ленни}
{1080}{}{Вууз}
{1090}{}{Гарольд}
{1100}{}{Mole Rat}
{1110}{}{Крутой Mole Rat}
{1120}{}{Крысокабан}
{1130}{}{Мощный крысокабан}
{1140}{}{Слабый брамин}
{1141}{}{Двуглавая мутант-корова.}
{1150}{}{Ул.силовая броня (don't use)}
{1160}{}{Мутировавшая Крыса}
{1161}{}{Мощная крыса-мутант.}
{1170}{}{Mutated Mole Rat}
{1171}{}{A tough mutant mole rat.}
{1180}{}{Мутировавший крысокабан}
{1181}{}{A tough mutant pig rat.}
{1190}{}{Супер Мутант}
{1200}{}{Мощный Мутант}
{1210}{}{Мелькор}
{1220}{}{Hero Andro (don't use)}
{1230}{}{Hero Andro (don't use)}
{1240}{}{Hero Male (don't use)}
{1250}{}{Hero Female (don't use)}
{1260}{}{Hero Male (don't use)}
{1270}{}{Hero Female (don't use)}
{1280}{}{Hero Male (don't use)}
{1290}{}{Hero Female (don't use)}
{1300}{}{Hero Male (don't use)}
{1310}{}{Hero Female (don't use)}
{1320}{}{Hero Male (don't use)}
{1330}{}{Hero Female (don't use)}
{1340}{}{Охранник Города Убежища}
{1350}{}{Охранник Города Убежища}
{1360}{}{Кибер-пес}
{1370}{}{Охранник НКР}
{1380}{}{Охранник НКР}
{1390}{}{Охранник НКР бьющийся в ближнем бою}
{1400}{}{Охранник Рабов}
{1410}{}{Надзиратель рабов}
{1420}{}{Торговец град-мастер}
{1430}{}{Торговец град-мастер}
{1440}{}{Танди}
{1450}{}{Мерк}
{1460}{}{Ратч}
{1470}{}{Скитер}
{1480}{}{Мики}
{1490}{}{Бармен НКР}
{1500}{}{Владелец магазина}
{1510}{}{Грутар}
{1520}{}{Горис}
{1530}{}{Molerat Fighter}
{1540}{}{Molerat Fighter}
{1550}{}{Molerat Fighter}
{1560}{}{Molerat Fighter}
{1570}{}{Molerat Fighter}
{1580}{}{Molerat Fighter}
{1590}{}{Уникальный Гуль}
{1600}{}{Майрон}
{1610}{}{Маркус}
{1620}{}{Док Джонс}
{1630}{}{Давин}
{1640}{}{Мириа}
{1650}{}{Лэдди}
{1660}{}{Рондо}
{1670}{}{Управлящий ранчо}
{1680}{}{Управлящий ранчо}
{1690}{}{Управлящий ранчо}
{1700}{}{Вышибала}
{1710}{}{Вышибала}
{1720}{}{Слабый Мистер Хэнди}
{1730}{}{Уникальное Свечение}
{1740}{}{Дар}
{1750}{}{Далия}
{1760}{}{Гордон}
{1770}{}{test (don't use)}
{1780}{}{Гуль реактора}
{1790}{}{Уникальный гуль}
{1800}{}{Матт}
{1810}{}{Охотник за головами}
{1820}{}{Охотник за головами}
{1830}{}{Охотник за головами}
{1840}{}{Охотник за головами}
{1850}{}{Охотник за головами}
{1860}{}{Охотник за головами}
{1870}{}{Охотник за головами}
{1880}{}{Охотник за головами}
{1890}{}{Охотник за головами}
{1900}{}{Охотник за головами}
{1910}{}{Бесс}
{1911}{}{Двуглавая корова-мутант.}
{1920}{}{Балтаз}
{1930}{}{Гришам}
{1940}{}{Фил}
{1950}{}{Курица}
{1960}{}{Карл}
{1970}{}{Джонни}
{1980}{}{Джо}
{1990}{}{Зеки}
{2000}{}{Бутчер}
{2010}{}{Пити}
{2020}{}{Примитивный охотник}
{2030}{}{Примитивный охотник}
{2040}{}{Каннибал}
{2050}{}{Каннибал}
{2060}{}{Послушник церкви}
{2070}{}{Послушница церкви}
{2080}{}{Nomad- Low}
{2090}{}{Nomad- Med}
{2100}{}{Nomad- Low}
{2110}{}{Nomad- Med}
{2120}{}{Бандит}
{2130}{}{Бандит}
{2140}{}{Фермер}
{2150}{}{Фермер}
{2160}{}{Мантис}
{2170}{}{Работорговец}
{2180}{}{Работорговец}
{2190}{}{Дикий брамин}
{2200}{}{Homesteader}
{2210}{}{Homesteader}
{2220}{}{Патруль Города Убежища}
{2230}{}{Патруль Города Убежища}
{2240}{}{Сильный работорговец}
{2250}{}{Сильный работорговец}
{2260}{}{Бешеные}
{2270}{}{Мусорщики}
{2280}{}{Светящийся Бешеный}
{2290}{}{Светящийся мусорщик}
{2300}{}{Рыболов}
{2310}{}{Рыбачка}
{2320}{}{Одичалый}
{2330}{}{Одичалый}
{2340}{}{Контрабандист}
{2350}{}{Контрабандист}
{2360}{}{Старатель}
{2370}{}{Старатель}
{2380}{}{Рейдер}
{2390}{}{Рейдер}
{2400}{}{Огненный Геккон}
{2410}{}{Мощный огненный геккон}
{2420}{}{Пришелец}
{2430}{}{Мощный пришелец}
{2440}{}{Огромный коготь смерти}
{2450}{}{Мощный коготь смерти}
{2460}{}{Летатель}
{2470}{}{Подлый летатель}
{2480}{}{Кентавр}
{2490}{}{Кентавр-мутант}
{2500}{}{Патруль анклава}
{2510}{}{Патруль анклава}
{2520}{}{Банда}
{2530}{}{Банда}
{2540}{}{Наемник}
{2550}{}{Наемник}
{2560}{}{Найткин}
{2570}{}{Мощный Найткин}
{2580}{}{Мощный Гуль}
{2590}{}{Гангстер}
{2600}{}{Якудза}
{2610}{}{Рейнджер НКР}
{2620}{}{Рейнджер НКР}
{2630}{}{Патруль братства}
{2640}{}{Патруль братства}
{2650}{}{Красавчик Ллойд}
{2660}{}{Ворпальная крыса}
{2670}{}{Житель убежища 13}
{2680}{}{Жительница убежища 13}
{2690}{}{Страж моста}
{2700}{}{Mysterious Stranger}
{2710}{}{Mysterious Stranger}
{2720}{}{Hakeswill}
{2730}{}{Хесус Мордино}
{2740}{}{Думар}
{2750}{}{Мать когтей смерти}
{2760}{}{Дракон}
{2770}{}{До Пан}
{2780}{}{Хаболог}
{2790}{}{Хаболог}
{2800}{}{Таинственный незнакомец}
{2810}{}{Таинственный незнакомец}
{2820}{}{Таинственный незнакомец}
{2830}{}{Таинственный незнакомец}
{2840}{}{Таинственный незнакомец}
{2850}{}{Таинственный незнакомец}
{2860}{}{Таинственный незнакомец}
{2870}{}{Таинственный незнакомец}
{2880}{}{Опытный телохранитель}
{2890}{}{Яйцо когтя смерти}
{2900}{}{Мецгер}
{2910}{}{Солдат Анклава}
{2920}{}{Солдат Анклава}
{2930}{}{Президент}
{2940}{}{Вице-президент}
{2950}{}{Техникон}
{2960}{}{Барсук}
{2970}{}{Доктор Фанг}
{2980}{}{Ребенок}
{2990}{}{Ребенок}
{3000}{}{Торговец оружием}
{3010}{}{Ученый Ши}
{3020}{}{Ши охранник}
{3030}{}{Ши Крестьянин}
{3040}{}{Ши Крестьянин}
{3050}{}{Ло Пан крестьянин}
{3060}{}{Ло Пан крестьянин}
{3070}{}{Работник доков}
{3080}{}{Ши Торговец}
{3090}{}{Кенг Раат}
{3100}{}{Сулик - Этап 1}
{3110}{}{Сулик - Этап 2}
{3120}{}{Сулик - Стадия 3}
{3130}{}{Сулик - Стадия 4}
{3140}{}{Сулик - Стадия 5}
{3150}{}{Сулик - Этап 6}
{3160}{}{Ленни - Этап 1}
{3170}{}{Ленни - Стадия 2}
{3180}{}{Ленни - Стадия 3}
{3190}{}{Горис - Этап 1}
{3200}{}{Горис - Этап 2}
{3210}{}{Горис - Этап 3}
{3220}{}{Горис - Этап 4}
{3230}{}{Горис - Этап 5}
{3240}{}{Горис - Этап 6}
{3250}{}{Мирон - Стадия 1}
{3260}{}{Мирон - Стадия 2}
{3270}{}{Мирон - Стадия 3}
{3280}{}{Мирон - Стадия 4}
{3290}{}{Маркус - Этап 1}
{3300}{}{Маркус - Этап 2}
{3310}{}{Маркус - Этап 3}
{3320}{}{Маркус - Этап 4}
{3330}{}{Маркус - Этап 5}
{3340}{}{Киберпес - Этап 1}
{3350}{}{Киберпес - Этап 2}
{3360}{}{Киберпес - Этап 3}
{3370}{}{Киберпес - Этап 4}
{3380}{}{Кэссиди - Этап 1}
{3390}{}{Кэссиди - Стадия 2}
{3400}{}{Кэссиди - Стадия 3}
{3410}{}{Кэссиди - Стадия 4}
{3420}{}{}Dogmeat
{3430}{}{Мясо собачье - стадия 1}
{3440}{}{Собачье мясо - Стадия 2}
{3450}{}{Собачье мясо - Стадия 3}
{3460}{}{Мясо собачье - Этап 4}
{3470}{}{Собачье мясо - Стадия 5}
{3480}{}{Собачье мясо - Этап 6}
{3490}{}{Робомозг - Этап 1}
{3500}{}{Робомозг - Этап 2}
{3510}{}{Робомозг - Этап 3}
{3520}{}{Робомозг - Этап 4}
{3530}{}{Робомозг - Этап 5}
{3540}{}{Королева пришельцев}
{3550}{}{Черный рад-скорпион}
{3560}{}{Черный рад-скорпион}
{3570}{}{Spud}
{3580}{}{Капитан наемников}
{3590}{}{Наемник}
{3600}{}{Наемник}
{3610}{}{Тень-преследователь}
{3620}{}{Панк}
{3630}{}{Панк}
{3640}{}{Марк}
{3650}{}{Дейв Х.}
{3660}{}{Капитан Рон Майерс}
{3670}{}{Чип}
{3680}{}{AHS-9}
{3690}{}{Хаболог-страж}
{3700}{}{Хаболог-страж}
{3710}{}{Джуан}
{3720}{}{Викки}
{3730}{}{Вик - Стадия 1}
{3740}{}{Вик - Стадия 2}
{3750}{}{Вик - Стадия 3}
{3760}{}{Вик - Стадия 4}
{3770}{}{Вик - Стадия 5}
{3780}{}{Вик - Стадия 6}
{3790}{}{Робомозг - Chimp}
{3800}{}{Робомозг - Abnormal}
{3810}{}{Робомозг - Human}
{3820}{}{Гиганский муравей}
{3830}{}{Мощный гиганский муравей }
{3840}{}{Бродячий пес}
{3850}{}{Зурак}
{3860}{}{Имбот}
{3870}{}{Джимми}
{3880}{}{Виджанг}
{3890}{}{Герб}
{3900}{}{Лупал}
{3910}{}{Джоби}
{3920}{}{Смитти}
{3930}{}{Руби}
{3940}{}{Мастер Кралл}
{3950}{}{Зигги}
{3960}{}{Мастер Хаг}
{3970}{}{Джон Бишоп}
{3980}{}{Андела Бишоп}
{3990}{}{Мистер Бишоп}
{4000}{}{Охранник Бишопов 1}
{4010}{}{Охранник Бишопов 2}
{4020}{}{Головорез Бишопов 1}
{4030}{}{Головорез Бишопов 2}
{4040}{}{Разъяренный брамин}
{4050}{}{Джесус Младший}
{4060}{}{Джесус Старший}
{4070}{}{Человек Мордино 1}
{4080}{}{Человек Мордино 2}
{4090}{}{Человек Мордино 3}
{4100}{}{Охранник Майрона 1}
{4110}{}{Охранник Майрона 2}
{4120}{}{Мистер Врайт}
{4130}{}{Миссис Врайт}
{4140}{}{Крисс Врайт}
{4150}{}{Кейт Врайт}
{4160}{}{Сын Врайта 1}
{4170}{}{Сын Врайта 2}
{4180}{}{Дочь Врайта 1}
{4190}{}{Дочь Врайта 2}
{4200}{}{Мистер Сальватор}
{4210}{}{Мейсон}
{4220}{}{Головорез Сальваторов 1}
{4230}{}{Головорез Сальваторов 2}
{4240}{}{Отличный бармен 1}
{4250}{}{Отличный бармен 2}
{4260}{}{Отличный бармен 3}
{4270}{}{Боксер 1}
{4280}{}{Боксер 2}
{4290}{}{Боксер 3}
{4300}{}{Боксер 4}
{4310}{}{Майк Мастик}
{4320}{}{Святой щит}
{4330}{}{Мс Кнелли}
{4340}{}{Стюарт Литтл}
{4350}{}{Корсиканские братья}
{4360}{}{Корсиканские братья}
{4370}{}{Отец Туллий}
{4380}{}{Вышибала 1}
{4390}{}{Вышибала 2}
{4400}{}{Девушка в казино}
{4410}{}{Торговец наркотиками/сутенер1}
{4420}{}{Торговец наркотиками/сутенер2}
{4430}{}{Торговец наркотиками/сутенер3}
{4440}{}{Торговец наркотиками/сутенер4}
{4450}{}{Мс Джи}
{4460}{}{Мисс Китти}
{4470}{}{Профессиональная шлюха 1}
{4480}{}{Профессиональная шлюха 2}
{4490}{}{Пьяный Джимми Джи }
{4500}{}{Ренеско}
{4510}{}{Ученый}
{4520}{}{Элдридж}
{4530}{}{Элджерн}
{4540}{}{Джулес}
{4550}{}{Бюрократ 1}
{4560}{}{Бюрократ 2}
{4570}{}{Торговец 1}
{4580}{}{Торговец 2}
{4590}{}{Охранник 1}
{4600}{}{Охранник 2}
{4610}{}{Охранник 3}
{4620}{}{Охранник 4}
{4630}{}{Солдат 1}
{4640}{}{Солдат 2}
{4650}{}{Солдат 3}
{4660}{}{Солдат 4}
{4670}{}{Сержант Старк}
{4680}{}{"Доктор" Эндрю}
{4690}{}{Бартер}
{4700}{}{Оружейная туррель}
{4701}{}{Это автоматическая орудийная башня, оснащенная двойной плазменной пушкой.}
{4710}{}{Усовершенствованный киборг}
{4720}{}{К-9 (стадия 1)}
{4730}{}{К-9 (стадия 2)}
{4740}{}{Оружейная турель}
{4750}{}{Рейнджер НКР}
{4760}{}{Рейнджер НКР}
{4770}{}{Яйцо ванаминго}
{4780}{}{Ло Пан охранник}
{4790}{}{Мэржори}
{4800}{}{Авто-туреть}
{4810}{}{Special Gecko Critter}
{4820}{}{Смерть с косой}
{4830}{}{Френк Хорриган}
{4831}{}{Телохранитель президента}
{4840}{}{Наемник-рукопаш}
{4850}{}{Наемник-рукопаш}
{4860}{}{Наемник-рукопаш}
{4870}{}{Наемник-рукопаш}
{4880}{}{Merc Misc}
{4890}{}{Наемник-легкач}
{4900}{}{Merc Misc}
{4910}{}{Merc SG}
{4920}{}{Наемник-рукопаш}
{4930}{}{Наемник-рукопаш}
{4940}{}{Наемник-рукопаш}
{4950}{}{Наемник-рукопаш}
{4960}{}{Наемник-тяж}
{4970}{}{Наемник-тяж}
{4980}{}{Наемник-тяж}
{4990}{}{Наемник-энергет}
{5000}{}{Наемник-энергет}
{5010}{}{Наемник Мутант}
{5020}{}{Наемник Мутант}
{5030}{}{Наемник Мутант}
{5040}{}{Наемник гуль-рукопаш}
{5050}{}{Наемник гуль-легкач}
{5060}{}{Пустынные сталкеры}
{5070}{}{Вечный скиталец }
{5080}{}{Bat}
{5090}{}{Жук}
{5100}{}{Пещерная крыса}
{5110}{}{Cougar}
{5120}{}{Cow}
{5130}{}{Венера человеко-ловка}
{5140}{}{Пустынный мантис}
{5150}{}{Thornslinger}
{5160}{}{Giant Wasp}
{5170}{}{Детеныш пришельца}
{5171}{}{Это пришелец выглядит новорожденным.}
{5180}{}{Солдат НКР}
{5190}{}{Солдат НКР}
{5200}{}{Огромная человеко-ловка}
{5210}{}{Одетая женщина}
{5220}{}{Ищейка}
{5230}{}{Брамин}
{5231}{}{Брамин из Браминьего забега}
{5240}{}{Mother Squeak-Squeak}
{5241}{}{The mighty Mother Squeak-Squeak, don't run, You'll only die tired.}
{5250}{}{Пасштур}
{5260}{}{Коготь Смерти}
{5270}{}{Мощный коготь смерти}
{5280}{}{Мать когтей смерти}
{5290}{}{Древний коготь смерти}
{5300}{}{Мистер помощник}
{5310}{}{Бот-ремонтник}
{5320}{}{Робомозг}
{5330}{}{Летающий робо-глаз}
{5340}{}{Охранный робот}
{5350}{}{Оружейная турель}
{5360}{}{Авто-турель}
{5370}{}{Лазерная турель}
{5380}{}{Female rebeliant}
{5381}{}{Female rebeliant}
{5390}{}{Rebeliant}
{5391}{}{Male rebeliant}
{5400}{}{Rebeliant}
{5401}{}{Male rebeliant}
{5410}{}{Melee female rebeliant}
{5411}{}{Female rebeliant}
{5420}{}{Long hair rebeliant}
{5421}{}{Long hair rebeliant}
{5430}{}{Bald rebeliant}
{5431}{}{Bald rebeliant}
{5440}{}{Женщина-ренегад}
{5441}{}{Женщина-ренегад}
{5450}{}{Мужчина-ренегад}
{5451}{}{Мужчина-ренегад}
{5460}{}{Мощная женщина-ренегад}
{5461}{}{Мощная женщина-ренегад}
{5470}{}{Мощный мужчина-ренегад}
{5471}{}{Мощный мужчина-ренегад}
{5480}{}{Лысый ренегад}
{5481}{}{Лысый ренегад}
{5490}{}{Илитный гвардеец Найткин}
{5491}{}{Илитный гвардеец Найткин}
{5500}{}{Илитный гвардеец Супермутант}
{5501}{}{Илитный гвардеец Супермутант}
{5510}{}{Лидер-Маршал гвардии}
{5511}{}{Лидер-Маршал гвардии}
{5520}{}{Мощный илитный гвардеец Найткин}
{5521}{}{Мощный илитный гвардеец Найткин}
{5530}{}{Мощный илитный гвардеец Супермутант}
{5531}{}{Мощный илитный гвардеец Супермутант}
{5540}{}{Девушка-воин}
{5541}{}{Девушка-воин}
{5550}{}{Мужчина-воин}
{5560}{}{Девушка-воин}
{5570}{}{Мужчина-воин}
{5580}{}{Bald Black Mad Warrior}
{5590}{}{Long Hair Mad Warrior}
{5600}{}{Long Hair Tough Mad Warrior}
{5610}{}{Bald Mad Warrior}
{5620}{}{Коготь смерти Мелькора}
{5630}{}{Огненный геккон Мелькора}
{5640}{}{Кентавр Мелькора}
{5650}{}{Летатель Мелькора}
{5660}{}{Мелькора}
{5670}{}{Фиолетовый последователь Кольта}
{5671}{}{Сын Кольта}
{5680}{}{Голубой последователь Кольта}
{5690}{}{Коричневый последователь Кольта}
{5700}{}{Черный последователь Кольта}
{5710}{}{Песчаный последователь Кольта}
{5720}{}{Вечный скиталец}
{5730}{}{Мощный вечный скиталец}
{5740}{}{Вечный скиталец охранник}
{5750}{}{Мощный вечный скиталец охранник}
{5760}{}{Мистер помощник}
{5770}{}{Улучшеный мистер помощник}
{5780}{}{Робомозг}
{5790}{}{Адаптированный робомозг}
{5800}{}{Робоглаз}
{5810}{}{Усовершенствованный робоглаз}
{5820}{}{Робот охранник}
{5830}{}{Откорректированный робот охранник}
{5840}{}{Улучшенный робот}
{5850}{}{Альфа кротокрыс}
{5860}{}{Мутировавший кротокрыс}
{5870}{}{Мутировавший крысокабан}
{5880}{}{Мутировавшая крыса}
{5890}{}{Начальник каравана}
{5900}{}{Пустынный охотник мужчина}
{5910}{}{Пустынный охотник женщина}
{5920}{}{Охранный робот мк II}
{5930}{}{Супер-охранный робот}
{5940}{}{Рейдер-убежища}
{5950}{}{Рейдер-убежища}
{5960}{}{Рейдер-убежища}
{5970}{}{Рейдер-убежища}
{5980}{}{Рейдер-убежища}
{5990}{}{Рейдер-убежища}
{8000}{}{Мать кентавров}
{8010}{}{Мать летателей}
{8020}{}{Мать пришельцев}
{8030}{}{Отец когтей смерти}
{8040}{}{Мать огненных гекко}
{8050}{}{Мать гекко}
{8060}{}{R.R.R.R. Agency Man}
{8061}{}{Rick Ron Roy Robbers Agency}
{8070}{}{R.R.R.R. Agency Green Hair}
{8071}{}{Rick Ron Roy Robbers Agency}
{8080}{}{R.R.R.R. Agency Woman}
{8081}{}{Rick Ron Roy Robbers Agency}
{8090}{}{R.R.R.R. Agency Long Hair}
{8091}{}{Rick Ron Roy Robbers Agency}
{8100}{}{R.R.R.R. Agency Bald Man}
{8101}{}{Rick Ron Roy Robbers Agency}
{8110}{}{Ronin Long Hair}
{8120}{}{Ronin Bald Man}
{8130}{}{Ronin Man}
{8140}{}{Зависимые шахтеры}
{8150}{}{Падший Паладин.}
{8160}{}{Падший Паладин.}
{8170}{}{Падший Паладин.}
{8180}{}{Падший Паладин.}
{8190}{}{Падший Паладин.}
{8200}{}{Падший Паладин.}
{8210}{}{Падший Паладин.}
{8220}{}{Падший Паладин.}
{8230}{}{Падший Паладин.}
{8240}{}{Падший Паладин.}
{8250}{}{Закрытый страж - NeedlerPistol_APammo}
{8260}{}{Locker Guard - HK Caws_fioletowe}
{8270}{}{Locker Guard - Ripper}
{8280}{}{Locker Guard - Laser Rifle}
{8290}{}{Locker Guard - Minigun_APammo}
{8300}{}{Locker Guard - P90_AP}
{8310}{}{Crater Ghoul - Claw}
{8320}{}{Crater Ghoul - HK Caws}
{8330}{}{Crater Ghoul - Assult Rifle}
{8340}{}{Crater Ghoul - FN FAL HPFA}
{8350}{}{Crater Ghoule - 223 pistol}
{8360}{}{Crater Ghoul - SMG}
{8370}{}{Crater Ghoul - Hunting rifle}
{8380}{}{Crater Ghoul - Ripper}
{8390}{}{Crater Ghoul - Combat Shotgun}
{8400}{}{Crater Ghoul - Greas Gun}
{8410}{}{Мутант Ареса - Лазерное ружье}
{8420}{}{Мутант Ареса - М60}
{8430}{}{Мутант Ареса - ЛПП}
{8440}{}{Мутант Ареса - Улучшеный огнемет}
{8450}{}{Мутант Ареса - Плазменное ружье}
{8460}{}{Мутант Ареса - Миниган}
{8470}{}{Мутант Ареса - Мститель}
{8480}{}{Мутант Ареса - MidBoss Gatling Laser}
{8490}{}{Мутант Ареса - Бозар}
{8500}{}{Мутант Ареса - Импульсное ружное YK42}
{8510}{}{Мутант Ареса - Boss Vindicator}
{8520}{}{Мутант Ареса - Ракетная установка}
{8530}{}{Канализационный мусорщик}
{8540}{}{Канализационный мусорщик}
{8550}{}{Канализационный мусорщик}
{8560}{}{Канализационный мусорщик}
{8570}{}{Канализационный мусорщик}
{8580}{}{Канализационный мусорщик}
{8590}{}{Мощный работорговец}
{8600}{}{Слабный работорговец}
{8610}{}{Жестокий работорговец}
{8620}{}{Работорговец-садист}
{8630}{}{Лидер Работорговцев}
{8640}{}{Работорговец ветеран}
{8650}{}{Рейдер новичек}
{8660}{}{Рейдер}
{8670}{}{Опытный рейдер}
{8680}{}{Рейдер Оверлорд}
{8690}{}{Рейдеры призывник}
{8700}{}{Combat Mech Mk.I}
{8710}{}{Combat Mech Mk.II}
{8720}{}{BDS Eyebot}
{8721}{}{Base-Defense Eyebot Secruity System}
{8730}{}{Utility Melee Robobrain}
{8740}{}{Prototype Cyborg}
{8750}{}{The Emperor}
{8751}{}{Лидер Культа.}
{8760}{}{Железный кулак}
{8770}{}{Судья}
{8780}{}{Культист Энфорсер}
{8790}{}{Культист Посвященный}
{8800}{}{Психованный рейдер}
{8810}{}{Сумасшедший}
{8820}{}{Моб}
{8821}{}{Смотритель убежища}
{8830}{}{Моб}
{8831}{}{Паук!}
{8840}{}{Моб}
{8841}{}{Девушка в черном комбинезоне с черепами}
{8850}{}{Моб}
{8851}{}{Мужчина в черном спортивном костюме с черепами}
{8860}{}{Моб}
{8861}{}{Мужчина в боевом доспехе Братства}
{8870}{}{Моб}
{8871}{}{Женщина в боевом доспехе Братства}
{8880}{}{Моб}
{8881}{}{Женщина в боевой броне Анклава}
{8890}{}{моб}
{8891}{}{Мужчина в боевой броне Анклава}
{8900}{}{Моб}
{8901}{}{Черный мужчина в металлической броне}
{8910}{}{Моб}
{8911}{}{Женщина в кожаном доспехе МК2}
{8920}{}{Моб}
{8921}{}{Мужчина в кожаном доспехе MK2}
{8930}{}{Моб}
{8931}{}{Моб в закаленной силовой броне}
{8940}{}{Моб}
{8941}{}{Мужчина в полицейской форме}
{8950}{}{Моб}
{8951}{}{Женщина в полицейской форме}
{8960}{}{Злой гуль}
{8970}{}{Моб}
{8971}{}{Длинноволосый мужчина в кожаной броне}
{8980}{}{Моб}
{8981}{}{Длинноволосый мужчина в комбинезоне убежища}
{8990}{}{моб}
{8991}{}{мужчина в комбинезоне убежища}
{9000}{}{Моб}
{9001}{}{Женщина в комбинезоне убежища}
{9010}{}{Моб}
{9011}{}{Смотритель убежища}
{9020}{}{Пони!}
{9021}{}{Выходец их Понивиля}
{18590}{}{Солдат Анклава}
{18591}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18600}{}{Солдат Анклава}
{18601}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18610}{}{Солдат Анклава}
{18611}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18620}{}{Солдат Анклава}
{18621}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18630}{}{Солдат Анклава}
{18631}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18640}{}{Солдат Анклава}
{18641}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18650}{}{Солдат Анклава}
{18651}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18660}{}{Ученый Анклава}
{18661}{}{Ученые Анклава отвечают за исследования и разработку технологий для Анклава, охватывающих все области исследований.}
{18670}{}{Техник Анклава}
{18671}{}{Техники Анклава являются членами технического и обслуживающего персонала Анклава.}
{18680}{}{Офицер Анклава}
{18681}{}{Солдаты Анклава являются основной пехотой Вооруженных Сил Анклава и в настоящее время являются самыми жесткими, сильными и самыми обучеными солдатами.}
{18690}{}{Пленник Анклава}
{18691}{}{Заключенный на нефтяной вышке Анклава.}
{18700}{}{Пленник Анклава}
{18701}{}{Заключенный на нефтяной вышке Анклава.}
{18710}{}{Пленник Анклава}
{18711}{}{Заключенный на нефтяной вышке Анклава.}
{18720}{}{Пленник Анклава}
{18721}{}{Заключенный на нефтяной вышке Анклава.}
{18730}{}{Пленник Анклава}
{18731}{}{Заключенный на нефтяной вышке Анклава.}
{18740}{}{Сулик}
{18741}{}{Он следует за избранным.}
{18750}{}{Вик}
{18751}{}{Он следует за избранным.}
{18760}{}{Турель Анклава}
{18761}{}{Башни анклава оснащены тяжелыми двойными миниганами, которые могут с легкостью разрывать даже силовую броню, что затрудняет борьбу с ними.}
{18770}{}{Робоглаз Анклава}
{18771}{}{Как правило, робоглаз - это робот-разведчик, который извергает пропаганду и ведет наблюдение благодаря радио-антеннам, направленными на его спину, и динамиками спереди.}
{18780}{}{Охранный робот анклава}
{18781}{}{Функционирующие боевые роботы, вооруженные миниганами и ракетами, найденными в Новой Калифорнии в 2241 году.}
{18790}{}{Френк Хорриган}
{18791}{}{Мощный супермутант в силовой броне.}
{18800}{}{Турель Анклава}
{18801}{}{Башни анклава оснащены тяжелыми двойными миниганами, которые могут с легкостью разрывать даже силовую броню, что затрудняет борьбу с ними.}
{18810}{}{Навесная башня}
{18811}{}{Башни анклава оснащены тяжелыми двойными миниганами, которые могут с легкостью разрывать даже силовую броню, что затрудняет борьбу с ними.}
{18820}{}{Мастер}
{18821}{}{ужасно мутировавший человек, что стоит за созданием армии мутантов}
{18830}{}{Патруль братства.}
{18840}{}{Патруль анклава.}
{18850}{}{Мутант НКР.}
{18860}{}{Робот Города Убежища.}
{90210}{}{Хранитель моста}
{90211}{}{По некоторым причинам, я думаю, что вы должны сохранить свою игру в новом слоте.}
{90220}{}{Бешеный гуль}
{90230}{}{Бешеный гуль}
{90240}{}{Бешеный гуль}
{90250}{}{Бешеный гуль}
{90260}{}{Крысокабан}
{90270}{}{Крысокабан}
{90280}{}{Крыса}
{90290}{}{Крыса}
{90300}{}{Ходячий мертвец}
{90310}{}{Ходячий мертвец}
{90320}{}{Ходячий мертвец}
{90330}{}{Ходячий мертвец}
{90340}{}{Ходячий мертвец}
{90350}{}{Ходячий мертвец}
{90360}{}{Пустынный сталкер}
{90370}{}{Пустынный сталкер}
{90380}{}{Коготь смерти}
{90390}{}{Коготь смерти}
{90400}{}{Мать когтей смерти}
{90410}{}{Новорожденный коготь смерти}
{90420}{}{Пришелец}
{90430}{}{Пришелец}
{90440}{}{Пришелец}
{90450}{}{Пришелец}
{90460}{}{Королева пришельцев}
