{1}{}{PID_METAL_PARTS@Various irregular pieces of metal, all shapes and sizes. Nothing special, but you suppose it could be turned into something worthwhile given the right expertise and equipment.@@@PID_METAL_ORE 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_PARTS 1@exp 10 script fix_boy@fix_Resource}
{2}{}{PID_GUNPOWDER@A box with a black powder.@@@PID_MINERAL 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GUNPOWDER 1@exp 5 script fix_boy@fix_Resource}
{3}{}{PID_ALLOYS@Some alloys. You could use them for repairing and upgrading equipment, or any other engineering projects.@@@PID_MINERAL 2&PID_METAL_ORE 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ALLOYS 1@exp 20 script fix_boy@fix_Resource}
{4}{}{PID_METAL_PARTS2@Various irregular pieces of good metal, all shapes and sizes. Nothing special, but you suppose it could be turned into something worthwhile given the right expertise and equipment.@@@PID_ORE2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_PARTS2 1@exp 10 script fix_boy@fix_Resource}
{5}{}{PID_GUNPOWDER2@A box with a better black powder.@@@PID_MINERALS2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GUNPOWDER2 1@exp 10 script fix_boy@fix_Resource}
{6}{}{PID_ALLOYS2@Alloys of a very good quality. You could use them for repairing and upgrading equipment, or any other engineering projects@@@PID_MINERALS2 1&PID_ORE2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ALLOYS2 1@exp 20 script fix_boy@fix_Resource}
{7}{}{PID_SAND_ROBE@A generic sand colored robe.@@@PID_FIBER 3&PID_GECKO_PELT 1&PID_BRAHMIN_HIDE 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SAND_ROBE 1@exp 120 script fix_boy@fix_Generic}
{8}{}{PID_PURPLE_ROBE@A generic purple colored robe.@@@PID_FIBER 3&PID_GOLDEN_GECKO_PELT 1&PID_BRAHMIN_HIDE 1&PID_CHEMICALS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_PURPLE_ROBE 1@exp 200 script fix_boy@fix_Generic}
{9}{}{PID_LEATHER_JACKET@A black, heavy leather jacket.@@@PID_FIBER 1&PID_GECKO_PELT 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LEATHER_JACKET 1&PID_LEATHER_JACKET_HELMET 1@exp 250 script fix_boy@fix_Generic}
{10}{}{PID_CURED_LEATHER_ARMOR@This heavily padded leather jacket is unusual in that it has two sleeves. You'll definitely make a fashion statement whenever, and wherever, you rumble.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 2@PID_FIBER 1&PID_GECKO_PELT 5&PID_GOLDEN_GECKO_PELT 1&PID_LEATHER_JACKET 1&PID_LEATHER_JACKET_HELMET 1&PID_BLUEPRINT_COMBAT_JACKET 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_CURED_LEATHER_ARMOR 1&PID_COMBAT_LEATHER_JACKET_HELMET 1@exp 500 script fix_boy@fix_Generic}
{11}{}{PID_LEATHER_ARMOR@Your basic all leather apparel. Finely crafted from tanned brahmin hide.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GOLDEN_GECKO_PELT 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LEATHER_ARMOR 1&PID_LEATHER_ARMOR_HELMET 1@exp 300 script fix_boy@fix_Generic}
{12}{}{PID_LEATHER_ARMOR_MK_II@An enhanced version of the basic leather armor with extra layers of protection. Finely crafted from tanned brahmin hide.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1&SK_REPAIR 80@PID_LEATHER_ARMOR 1&PID_GOLDEN_GECKO_PELT 1&PID_FIBER 2&PID_BRAHMIN_HIDE 1&PID_LEATHER_ARMOR_HELMET 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LEATHER_ARMOR_MK_II 1&PID_LEATHER_ARMOR_HELMET_MK2 1@exp 400 script fix_boy@fix_Generic}
{13}{}{PID_FIREGECKO_JACKET@Leather Armor highly resistant to fire made from the skin of fire gecko.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 80@PID_LEATHER_ARMOR 1&PID_FIREGECKO_PELT 1&PID_FIBER 2&PID_LEATHER_ARMOR_HELMET 1&PID_BLUEPRINT_FIREGECKO_JACKET 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FIREGECKO_JACKET 1&PID_LEATHER_ARMOR_HELMET_MK2 1@exp 500 script fix_boy@fix_Generic}
{14}{}{PID_METAL_ARMOR@Polished metal plates, crudely forming a suit of armor.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1&SK_REPAIR 100@PID_FIBER 1&PID_BRAHMIN_HIDE 1&PID_METAL_PARTS 4&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_ARMOR 1&PID_METAL_HELMET 1@exp 250 script fix_boy@fix_Generic}
{15}{}{PID_METAL_ARMOR_MK_II@Polished metal plates, finely crafted into a suit of armor.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_PARTS2 3&PID_METAL_ARMOR 1&PID_FIBER 1&PID_BLUEPRINT_METAL_ARMOR_MK_II 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_ARMOR_MK_II 1&PID_METAL_HELMET_MK2 1@exp 1000 script fix_boy@fix_Blueprint}
{16}{}{PID_METAL_ARMOR_MK_III@A heavily and professionally reinforced set of metal armor, this heavy duty piece of master craftmanship will provide adequate protection against most damage types and exceptional protection to most laser based attacks.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_FIBER 1&PID_ALLOYS2 1&PID_METAL_PARTS2 2&PID_BLUEPRINT_METAL_ARMOR_MK_III 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_METAL_ARMOR_MK_III 1&PID_METAL_HELMET_MK2 1@exp 900 script fix_boy@fix_Blueprint}
{17}{}{PID_TESLA_ARMOR@This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 4&PID_BLUEPRINT_TESLA_ARMOR 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_TESLA_ARMOR 1&PID_METAL_HELMET_MK2 1@exp 500 script fix_boy@fix_Blueprint}
{18}{}{PID_INFERNO_ARMOR@Technologically advanced armor, made of high quality plates,there have been used the heat resistant components. Type of armor made for protection from fire and burns.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_ALLOYS2 1&PID_ADV_SUPERBURN 2&PID_BLUEPRINT_INFERNO_ARMOR 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_INFERNO_ARMOR 1&PID_METAL_HELMET_MK2 1@exp 400 script fix_boy@fix_Blueprint}
{19}{}{PID_MUT_METAL@It is crude armor that uses straps of leather and metal bands to form a sparse but effective covering.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_BLUEPRINT_MUT_ARMOR 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_MUT_METAL 1&PID_METAL_HELMET_MK2 1@exp 1000 script fix_boy@fix_Blueprint}
{20}{}{PID_COMBAT_ARMOR@High tech armor, made out of advanced defensive polymers.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 1&SK_REPAIR 100@PID_ALLOYS2 3&PID_METAL_PARTS 1&PID_FIBER 1&PID_FIREGECKO_PELT 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_COMBAT_ARMOR 1&PID_COMBAT_HELMET 1@exp 850 script fix_boy@fix_Blueprint}
{21}{}{PID_COMBAT_ARMOR_MK_II@High tech armor, made out of advanced defensive polymers.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_METAL_PARTS2 3&PID_BLUEPRINT_COMBAT_ARMOR_MK_II 1@PID_ADVANCED_BENCH 1@PID_COMBAT_ARMOR_MK_II 1&PID_COMBAT_HELMET_MK_II 1@exp 1200 script fix_boy@fix_Blueprint}
{22}{}{PID_BROTHERHOOD_COMBAT_ARMOR@A superior version of Combat Armor. The Brotherhood of Steel have made many improvements over the standard version.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_ELECTRONIC_PARTS 2&PID_GECKO_PELT 1&PID_BLUEPRINT_BROTHERHOOD_COMBAT_ARMOR 1@PID_ADVANCED_BENCH 1@PID_BROTHERHOOD_COMBAT_ARMOR 1&PID_BROTHERHOOD_HELMET 1@exp 1000 script fix_boy@fix_Blueprint}
{23}{}{PID_ENCLAVE_COMBAT_ARMOR@The prototype of a superior version of Combat Armor, developed by the Enclave. Its advanced polycarbon materials allow it a better protection against energy attacks.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_ENCLAVE_COMBAT_ARMOR 1@PID_ADVANCED_BENCH 1@PID_ENCLAVE_COMBAT_ARMOR 1&PID_ENCLAVE_COMBAT_HELMET 1@exp 1000 script fix_boy@fix_Blueprint}
{24}{}{PID_DESERT_COMBAT_ARMOR@Combat armor ensuring better protection against sand and dust during operations in the desert. In addition, sand-colored hues for better camouflage.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 6&PID_BLUEPRINT_DESERT_COMBAT_ARMOR 1@PID_ADVANCED_BENCH 1@PID_DESERT_COMBAT_ARMOR 1&PID_DESERT_COMBAT_HELMET 1@exp 900 script fix_boy@fix_Blueprint}
{25}{}{PID_NCR_ARMOR@High tech armor, made out of advanced defensive polymers. This one is modified for the Rangers of the New California Republic.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_FIREGECKO_PELT 1&PID_BLUEPRINT_NCR_ARMOR 1@PID_ADVANCED_BENCH 1@PID_NCR_ARMOR 1&PID_NCR_HELMET 1@exp 1000 script fix_boy@fix_Blueprint}
{26}{}{PID_CLOTHES_POLICE@Vault City combat armor made of high quality polymers, Type of armor made for protection from critical hits.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 6&PID_ALLOYS 3&PID_BLUEPRINT_CLOTHES_POLICE 1@PID_ADVANCED_BENCH 1@PID_CLOTHES_POLICE 1&PID_VC_HELMET 1@exp 1200 script fix_boy@fix_Blueprint}
{27}{}{PID_BBS@A package of BB's from before the war. In excellent condition. Stainless steel.@@@PID_PUMP_PARTS 4@@PID_BBS 50@exp 20 script fix_boy@fix_Generic}
{28}{}{PID_9MM_BALL@A collection of ancient 9x19mm rounds. Heavy grease to preserve them from the environment. Standard bullets.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 4&PID_PUMP_PARTS 1@@PID_9MM_BALL 100@exp 90 script fix_boy@fix_Generic}
{29}{}{PID_10MM_JHP@Ammunition. Caliber: 10mm, jacketed hollow-points@@@PID_METAL_PARTS 1&PID_GUNPOWDER 8@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_JHP 100@exp 150 script fix_boy@fix_Generic}
{30}{}{PID_10MM_AP@Ammunition. Caliber: 10mm, armor piercing.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_AP 100@exp 180 script fix_boy@fix_Generic}
{31}{}{PID_44_MAGNUM_JHP@A brick of ammunition, .44 Magnum caliber, hollow-points.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_MAGNUM_JHP 100@exp 180 script fix_boy@fix_Generic}
{32}{}{PID_44_FMJ_MAGNUM@A brick of ammunition, .44 Magnum caliber, full metal jacket.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_FMJ_MAGNUM 100@exp 180 script fix_boy@fix_Generic}
{33}{}{PID_45_CALIBER_AMMO@Ammunition. .45 Caliber.@@@PID_PUMP_PARTS 1&PID_GUNPOWDER 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_45_CALIBER_AMMO 100@exp 80 script fix_boy@fix_Generic}
{34}{}{PID_HN_NEEDLER_CARTRIDGE@Ammunition. This cartridge appears to be ammo for the HN Needler Pistol. Each 'bullet' is a small hypodermic designed to inject a target with its contents upon impact.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_HN_NEEDLER_CARTRIDGE 100@exp 50 script fix_boy@fix_Generic}
{35}{}{PID_HN_AP_NEEDLER_CARTRIDGE@Ammunition. This cartridge appears to be armor-piercing ammo for the HN Needler Pistol. The hypodermic tips are made of a strange alloy and are incredibly sharp.@PE_PROFESSION_DOCTOR 2|PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_DOCTOR 2|PE_PROFESSION_GUNSMITH_S 2@PID_METAL_PARTS2 1&PID_GUNPOWDER2 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_HN_AP_NEEDLER_CARTRIDGE 100@exp 300 script fix_boy@fix_Generic}
{36}{}{PID_SHOTGUN_SHELLS@12 ga. Shotgun Shells@@@PID_METAL_PARTS 1&PID_GUNPOWDER 9@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS 100@exp 150 script fix_boy@fix_Generic}
{37}{}{PID_SHOTGUN_SHELLS_SLUG@12 ga. Shotgun Shells (Slug)@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 2&PID_GUNPOWDER2 8@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS_SLUG 100@exp 200 script fix_boy@fix_Generic}
{38}{}{PID_SHOTGUN_SHELLS_FLECHETTE@12 ga. Shotgun Shells (Flechette)@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_PUMP_PARTS 2&PID_METAL_PARTS2 1&PID_GUNPOWDER2 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS_FLECHETTE 100@exp 400 script fix_boy@fix_Generic}
{39}{}{PID_SHOTGUN_SHELLS_EMP@12 ga. Shotgun Shells (EMP)@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 120@PID_METAL_PARTS2 1&PID_GUNPOWDER2 2&PID_ELECTRONIC_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS_EMP 100@exp 500 script fix_boy@fix_Generic}
{40}{}{PID_SHOTGUN_DRAGON_BREATH_SHELLS@Shotgun fire ammunition. It consists primarily of magnesium pellets/shards. When the round is fired, sparks and flames can shoot out to about 30 meters.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 175@PID_GUNPOWDER3 1&PID_FIREGECKO_PELT 10&PID_BLUEPRINT_SHOTGUN_DRAGON_BREATH_SHELLS 1@PID_ADVANCED_BENCH 1@PID_SHOTGUN_DRAGON_BREATH_SHELLS 100@exp 15000 script fix_boy@fix_Blueprint}
{41}{}{PID_14MM_AP@Large caliber ammunition. 14mm armor piercing.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_14MM_AP 100@exp 110 script fix_boy@fix_Generic}
{42}{}{PID_223_FMJ@A case of ammunition, .223 caliber, Full Metal Jacket.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_223_FMJ 100@exp 130 script fix_boy@fix_Generic}
{43}{}{PID_5MM_JHP@A brick of small, lightweight ammunition. Caliber: 5mm, jacketed hollow-point.@PE_PROFESSION_GUNSMITH_B 1|PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_B 1|PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_5MM_JHP 100@exp 90 script fix_boy@fix_Generic}
{44}{}{PID_5MM_AP@A brick of small caliber ammunition. 5mm armor piercing.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 2&PID_GUNPOWDER2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_5MM_AP 100@exp 80 script fix_boy@fix_Generic}
{45}{}{PID_7_62MM_AMMO@Ammunition. Caliber: 7.62mm.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_7_62MM_AMMO 100@exp 180 script fix_boy@fix_Generic}
{46}{}{PID_40MM_GRENADE@A grenade for a grenade launcher@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 1&PID_GUNPOWDER 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_40MM_GRENADE 10@exp 110 script fix_boy@fix_Generic}
{47}{}{PID_FLAMETHROWER_FUEL@A cylinder containing an extremely flammable liquid fuel for flamethrowers.@@@PID_ROT_GUT 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FLAMETHROWER_FUEL 120@exp 80 script fix_boy@fix_Generic}
{48}{}{PID_ADV_SUPERBURN@A component of the flamethrower fuel. Makes fuel even more hot and dangerous.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_GUNPOWDER2 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ADV_SUPERBURN 1@exp 40 script fix_boy@fix_Generic}
{49}{}{PID_FLAMETHROWER_FUEL_MK_II@This flamethrower fuel uses an advanced super-burn mix.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ADV_SUPERBURN 1&PID_FLAMETHROWER_FUEL 40@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FLAMETHROWER_FUEL_MK_II 40@exp 80 script fix_boy@fix_Generic}
{50}{}{PID_EXPLOSIVE_ROCKET@A rocket with a large explosive warhead.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 1&PID_GUNPOWDER 6&PID_PUMP_PARTS 1@PID_ADVANCED_BENCH 1@PID_EXPLOSIVE_ROCKET 10@exp 125 script fix_boy@fix_Generic}
{51}{}{PID_NAPALM@This flame thrower has a build in high pressure compressor which greatly increase its effective firing distance.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_CARBON_POLYMER 1&PID_ROTARY_CHAMBER 2&PID_TECH_SEMI_TRIGGER 1&PID_ABSORBER 1&PID_BLUEPRINT_NAPALM 1@PID_MACHINERY_SMALL_GUNS 1@PID_NAPALM 1@exp 25000 script fix_boy@fix_Blueprint}
{52}{}{PID_ROCKET_AP@A rocket shell, with a smaller explosive, but designed to pierce armor plating.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_ROCKET_AP 10@exp 180 script fix_boy@fix_Generic}
{53}{}{PID_EL_ROCKET@This rocket emits a strong electrical impulse upon impact effectively electrocuting anyone in its blast radius.@@@PID_ELECTRONIC_PARTS 2&PID_GUNPOWDER2 5@PID_ADVANCED_BENCH 1@PID_EL_ROCKET 10@exp 200 script fix_boy@fix_Generic}
{54}{}{PID_ROBO_ROCKET_AMMO@Isn't exists in this game yet.@PE_PROFESSION_ENERGY_EXPERT 4|PE_PROFESSION_GUNSMITH_B 4@PE_PROFESSION_ENERGY_EXPERT 4|PE_PROFESSION_GUNSMITH_B 4&SK_SCIENCE 175@PID_METAL_PARTS 7&PID_ALLOYS 15&PID_METAL_PARTS2 9&PID_ALLOYS2 7&PID_GUNPOWDER2 15&PID_ELECTRONIC_PARTS2 7&PID_TECH_CONDEN 7&PID_BLUEPRINT_ROBO_ROCKET_AMMO 1@PID_WORKBENCH_FAT_HI_AMMO 1@PID_ROBO_ROCKET_AMMO 1@exp 300 script fix_boy@fix_Blueprint}
{55}{}{PID_SMALL_ENERGY_CELL@A small, self-contained energy storage unit.@@SK_SCIENCE 120@PID_ALLOYS 2&PID_ELECTRONIC_PARTS 4@PID_ADVANCED_BENCH 1@PID_SMALL_ENERGY_CELL 100@exp 250 script fix_boy@fix_Generic}
{56}{}{PID_MICRO_FUSION_CELL@A medium sized energy production unit. Self-contained fusion plant.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 150@PID_REFINED_ORE 3&PID_ALLOYS 1&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_MICRO_FUSION_CELL 100@exp 350 script fix_boy@fix_Generic}
{57}{}{PID_4_7MM_CASELESS@Ammunition. Caliber: 4.7mm, caseless.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2&SK_SCIENCE 175@PID_GUNPOWDER3 1&PID_METAL_PARTS2 1&PID_BLUEPRINT_4_7MM_CASELESS 1@PID_ADVANCED_BENCH 1@PID_4_7MM_CASELESS 100@exp 15000 script fix_boy@fix_Blueprint}
{58}{}{PID_2MM_EC_AMMO@Ammunition. Caliber: 2mm, EC@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 175@PID_GUNPOWDER3 1&PID_CYLINDRICAL_LOCK 1&PID_BLUEPRINT_2MM_EC_AMMO 1@PID_ADVANCED_BENCH 1@PID_2MM_EC_AMMO 100@exp 15000 script fix_boy@fix_Blueprint}
{59}{}{PID_9MM_MAUSER@A Mauser M/96, in 9x19mm Parabellum. In excellent condition. Extremely accurate. @@@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_PUMP_PARTS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_9MM_MAUSER 1@exp 95 script fix_boy@fix_Generic}
{60}{}{PID_10MM_PISTOL@A Colt 6520 10mm autoloading pistol. Each pull of the trigger will automatically reload the firearm until the magazine is empty. Single shot only, using the powerful 10mm round. @@@PID_FIREWOOD 1&PID_METAL_PARTS 5&PID_ALLOYS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_PISTOL 1@exp 190 script fix_boy@fix_Generic}
{61}{}{PID_44_MAGNUM_REVOLVER@Being that this is the most powerful handgun in the world, and can blow your head clean-off, you've got to ask yourself one question. Do I feel lucky? Well, do ya punk? @PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_ALLOYS 2&PID_METAL_PARTS 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_MAGNUM_REVOLVER 1@exp 210 script fix_boy@fix_Generic}
{62}{}{PID_SPEED_LOADER@Useful thingy for faster reloading of a revolver.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_PUMP_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SPEED_LOADER 1@exp 5 script fix_boy@fix_Generic}
{63}{}{PID_44_MAGNUM_SPEEDLOADER@A .44 Magnum Revolver with a speed loader.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_44_MAGNUM_REVOLVER 1&PID_SPEED_LOADER 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 25 script fix_boy@fix_Generic}
{64}{}{PID_DESERT_EAGLE@An ancient Desert Eagle pistol, in .44 Magnum. Interest in late 20th century films made this one of the most popular handguns of all times. @PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 3&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_DESERT_EAGLE 1@exp 170 script fix_boy@fix_Generic}
{65}{}{PID_EXTENDED_MAGAZINE@An extended magazine, for those who dislike frequent reloading.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_PUMP_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_EXTENDED_MAGAZINE 1@exp 5 script fix_boy@fix_Generic}
{66}{}{PID_DESERT_EAGLE_EXT_MAG@An ancient Desert Eagle pistol, in .44 Magnum. Interest in late 20th century films made this one of the most popular handguns of all times. This one has been equipped with an expanded magazine for longer fun and games!@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_DESERT_EAGLE 1&PID_EXTENDED_MAGAZINE 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 30 script fix_boy@fix_Generic}
{67}{}{PID_NEEDLER_PISTOL@You suspect this Bringham needler pistol was once used for scientific field studies. It uses small hard-plastic hypodermic darts as ammo. @PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PID_FIREWOOD 1&PID_ALLOYS2 1&PID_ALLOYS 1&PID_METAL_PARTS 3&PID_METAL_PARTS2 1&PID_PUMP_PARTS 5&PID_BLUEPRINT_NEEDLER_PISTOL 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_NEEDLER_PISTOL 1@exp 600 script fix_boy@fix_Blueprint}
{68}{}{PID_14MM_PISTOL@A Sig-Sauer 14mm Auto Pistol. Large, single shot handgun. Excellent craftmanship. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS 3&PID_ALLOYS2 2&PID_BLUEPRINT_14MM_PISTOL 1@PID_ADVANCED_BENCH 1@PID_14MM_PISTOL 1@exp 500 script fix_boy@fix_Blueprint}
{69}{}{PID_223_PISTOL@A .223 rifle modified and cut down to a pistol. This is a one-of-a-kind firearm, obviously made with love and skill. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_HUNTING_RIFLE 1&PID_PUMP_PARTS 3&PID_ALLOYS2 1&PID_METAL_PARTS2 2&PID_BLUEPRINT_223_PISTOL 1@PID_ADVANCED_BENCH 1@PID_223_PISTOL 1@exp 800 script fix_boy@fix_Blueprint}
{70}{}{PID_PK12_GAUSS_PISTOL@Praised for its range and stopping power, the PPK12 Gauss Pistol is of German design. The pistol uses an electromagnetic field to propel rounds at tremendous speed and punch through almost any armor.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_TECH_AUTO_TRIGGER 1&PID_TECH_MECH_ENGINE 2&PID_TECH_PLASMA 3&PID_ELECTRIC_AMPLIFIER 1&PID_BLUEPRINT_PK12_GAUSS_PISTOL 1@PID_MACHINERY_SMALL_GUNS 1@PID_PK12_GAUSS_PISTOL 1@exp 35000 script fix_boy@fix_Blueprint}
{71}{}{PID_GREASE_GUN@This submachine gun filled National Guard arsenals after the Army replaced it with newer weapons. However, the "Grease Gun" was simple and cheap to manufacture so there are quite a few still in use.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 6@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GREASE_GUN 1@exp 200 script fix_boy@fix_Generic}
{72}{}{PID_10MM_SMG@H&K MP9 Submachinegun (10mm variant). A medium-sized SMG, capable of single shot and burst mode.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_ALLOYS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_SMG 1@exp 400 script fix_boy@fix_Generic}
{73}{}{PID_HK_P90C@The Heckler & Koch P90c was just coming into use at the time of the war. The weapon's bullpup layout, and compact design, make it easy to control. The durable P90c is prized for its reliability, and high firepower in a ruggedly-compact package.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 3&PID_ALLOYS2 1&PID_METAL_PARTS 4&PID_METAL_PARTS2 2&PID_BLUEPRINT_P90 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_HK_P90C 1@exp 800 script fix_boy@fix_Blueprint}
{74}{}{PID_HK_G11@This gun revolutionized assault weapon design. The weapon fires a caseless cartridge consisting of a block of propellant with a bullet buried inside.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_TECH_DELINER 1&PID_TECH_ELE_ENGINE 1&PID_TECH_CONDEN 1&PID_ELECTRIC_AMPLIFIER 1&PID_BLUEPRINT_HK_G11 1@PID_MACHINERY_SMALL_GUNS 1@PID_HK_G11 1@exp 20000 script fix_boy@fix_Blueprint}
{75}{}{PID_HK_G11E@This gun revolutionized squad level support weapon design. The gun fires a caseless cartridge consisting of a block of propellant with a bullet buried inside.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_HK_G11 1&PID_TECH_SCOPE 1&PID_TECH_MICROCHIPS 1&PID_BLUEPRINT_HK_G11E 1@PID_MACHINERY_SMALL_GUNS 1@PID_HK_G11E 1@exp 25000 script fix_boy@fix_Blueprint}
{76}{}{PID_RED_RYDER_BB_GUN@A Red Ryder BB gun. The classic. @@@PID_FIREWOOD 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_RED_RYDER_BB_GUN 1@exp 30 script fix_boy@fix_Generic}
{77}{}{PID_HUNTING_RIFLE@A Colt Rangemaster semi-automatic rifle, in .22 caliber. Single-shot only.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 4&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_HUNTING_RIFLE 1@exp 200 script fix_boy@fix_Generic}
{78}{}{PID_SCOPE@An all-weather optical scope in excellent condition.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SCOPE 1@exp 40 script fix_boy@fix_Generic}
{79}{}{PID_SCOPED_HUNTING_RIFLE@Nothing's better than seeing that surprised look on your target's face. The Loophole x20 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_HUNTING_RIFLE 1&PID_SCOPE 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SCOPED_HUNTING_RIFLE 1@exp 105 script fix_boy@fix_Generic}
{80}{}{PID_SNIPER_RIFLE@A DKS-501 Sniper Rifle. Excellent long range projectile weapon. Originally .308, this one is chambered in the more common .223 caliber.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 1&PID_ALLOYS 3&PID_METAL_PARTS 6&PID_METAL_PARTS2 3&PID_SCOPE 1&PID_BLUEPRINT_SNIPER_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_SNIPER_RIFLE 1@exp 1200 script fix_boy@fix_Blueprint}
{81}{}{PID_M72_GAUSS_RIFLE@The M72 rifle is of German design. It uses an electromagnetic field to propel rounds at tremendous speed... and pierce almost any obstacle. Its range, accuracy and stopping power is almost unparalleled.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_CARBON_POLYMER 1&PID_TECH_AUTO_TRIGGER 2&PID_TECH_CONDEN 1&PID_TECH_TRANSFORMATOR 2&PID_ABSORBER 1&PID_TECH_ELE_ENGINE 2&PID_BLUEPRINT_M72_GAUSS_RIFLE 1@PID_MACHINERY_SMALL_GUNS 1@PID_M72_GAUSS_RIFLE 1@exp 50000 script fix_boy@fix_Blueprint}
{82}{}{PID_TOMMY_GUN@This Thompson M1928 submachine gun is a sinister looking weapon; every time you hold it, you have an urge to put on a fedora hat and crack your knuckles. The Thompson is well-fed by a large 50 round drum magazine.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 3&PID_PUMP_PARTS 7@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_TOMMY_GUN 1@exp 145 script fix_boy@fix_Generic}
{83}{}{PID_ASSAULT_RIFLE@An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 4&PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_METAL_PARTS2 1&PID_BLUEPRINT_ASSAULT_RIFLE 1@PID_ADVANCED_BENCH 1@PID_ASSAULT_RIFLE 1@exp 750 script fix_boy@fix_Blueprint}
{84}{}{PID_ASSAULT_RIFLE_EXT_MAG@This Assault Rifle has an extended, military sized, ammunition clip. The expanded magazine capacity makes it more fun than ever to Spray-and-Pray.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ASSAULT_RIFLE 1&PID_EXTENDED_MAGAZINE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 200 script fix_boy@fix_Generic}
{85}{}{PID_FN_FAL@This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_ALLOYS 3&PID_ALLOYS2 2&PID_BLUEPRINT_FN_FAL 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_FN_FAL 1@exp 500 script fix_boy@fix_Blueprint}
{86}{}{PID_FN_FAL_HPFA@The FN FAL HPFA variant. This model has been tinkered with to increase its firepower making the gun much more dangerous, to both the user and his target.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FN_FAL 1&PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS2 2&PID_ALLOYS2 2@PID_ADVANCED_BENCH 1@PID_FN_FAL_HPFA 1@exp 1100 script fix_boy@fix_Generic}
{87}{}{PID_FN_FAL_NIGHT_SCOPE@This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation. This weapon has been equipped with a night sight for greater night accuracy.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 200&SK_REPAIR 175@PID_FN_FAL_HPFA 1&PID_SCOPE 1&PID_ALLOYS2 5&PID_BLUEPRINT_FN_FAL_NIGHT_SCOPE 1@PID_MACHINERY_SMALL_GUNS 1@PID_FN_FAL_NIGHT_SCOPE 1@exp 1300 script fix_boy@fix_Blueprint}
{88}{}{PID_INDEPENDENT@This was an experimental weapon at the time of the war. Manufactured, primarily, from high-strength polymers, the weapon is almost indestructible. It's light, fast firing, accurate, and can be broken down without the use of any tools.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS2 2&PID_ALLOYS2 2&PID_ALLOYS 3&PID_METAL_PARTS 4&PID_BLUEPRINT_INDEPENDENT 1@PID_ADVANCED_BENCH 1@PID_INDEPENDENT 1@exp 1200 script fix_boy@fix_Blueprint}
{89}{}{PID_SHOTGUN@A Winchester Widowmaker double-barreled 12-gauge shotgun. Short barrel, with mahogany grip.@@@PID_FIREWOOD 1&PID_METAL_PARTS 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN 1@exp 170 script fix_boy@fix_Generic}
{90}{}{PID_SAWED_OFF_SHOTGUN@Someone took the time to chop the last few inches off the barrel and stock of this shotgun. Now, the wide spread of this hand-cannon's short-barreled shots makes it perfect for short-range crowd control.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_SHOTGUN 1&PID_METAL_PARTS 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SAWED_OFF_SHOTGUN 1@exp 100 script fix_boy@fix_Generic}
{91}{}{PID_COMBAT_SHOTGUN@A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 6&PID_ALLOYS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_COMBAT_SHOTGUN 1@exp 220 script fix_boy@fix_Generic}
{92}{}{PID_HK_CAWS@The CAWS, short for Close Assault Weapons System, shotgun is a useful tool for close-range combat. The bullpup layout gives the weapon a short, easily handleable, length while still retaining enough barrel length for its high velocity shells.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 2&PID_ALLOYS 2&PID_METAL_PARTS 3&PID_PUMP_PARTS 3&PID_BLUEPRINT_HK_CAWS 1@PID_ADVANCED_BENCH 1@PID_HK_CAWS 1@exp 500 script fix_boy@fix_Blueprint}
{93}{}{PID_PANCOR_JACKHAMMER@The Jackhammer, despite its name, is an easy to control shotgun, even when fired on full automatic. The popular bullpup design, which places the magazine behind the trigger, makes the weapon well balanced & easy to control.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_METAL_PARTS2 2&PID_ALLOYS 3&PID_ALLOYS2 1&PID_BLUEPRINT_PANCOR_JACKHAMMER 1@PID_ADVANCED_BENCH 1@PID_PANCOR_JACKHAMMER 1@exp 800 script fix_boy@fix_Blueprint}
{94}{}{PID_SAIGA12@Imagine an AK-47 limited to semi-automatic fire with a rebuilt chamber to house shotgun shells and you have this automatic shotgun. Extremely powerful at short range it loses accuracy at longer ranges.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_TECH_DELINER 1&PID_TECH_GUN_CONTROL 2&PID_TECH_MICROCHIPS 1&PID_ARM_CARBON 3&PID_BLUEPRINT_SAIGA_12 1@PID_MACHINERY_SMALL_GUNS 1@PID_SAIGA12 1@exp 25000 script fix_boy@fix_Blueprint}
{95}{}{PID_GRENADE_PISTOL@Designed well before the great war, the Fabrique Nationale 69A1 pistol grenade launcher became the standard issue portable fire support system of the US military police units stationed in Canada during the conflict.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_ALLOYS 5&PID_METAL_PARTS 2&PID_FIREWOOD 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GRENADE_PISTOL 1@exp 180 script fix_boy@fix_Generic}
{96}{}{PID_GRENADE_LAUNCHER@A single shot grenade launcher.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ALLOYS 5&PID_FIREWOOD 1&PID_ALLOYS2 1&PID_METAL_PARTS2 2@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_GRENADE_LAUNCHER 1@exp 800 script fix_boy@fix_Generic}
{97}{}{PID_M16@American-powered automatic rifle, chambered in 5mm.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ALLOYS 3&PID_FIREWOOD 1&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_BLUEPRINT_M16 1@PID_ADVANCED_BENCH 1@PID_M16 1@exp 1000 script fix_boy@fix_Generic}
{98}{}{PID_FLAMER@A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly.@@@PID_FIREWOOD 1&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FLAMER 1@exp 150 script fix_boy@fix_Generic}
{99}{}{PID_HEATERCHAMBER@Enables the use of extremely heated fuel with the flamethrower.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2&SK_REPAIR 100@PID_METAL_PARTS2 1&PID_ALLOYS2 1@PID_ADVANCED_BENCH 1@PID_HEATERCHAMBER 1@exp 400 script fix_boy@fix_Generic}
{100}{}{PID_IMPROVED_FLAMETHROWER@A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly. This model has been modified to fire a hotter mixture which causes greater combustibility.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_FLAMER 1&PID_HEATERCHAMBER 1&PID_BLUEPRINT_IMPROVED_FLAMETHROWER 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_IMPROVED_FLAMETHROWER 1@exp 200 script fix_boy@fix_Blueprint}
{101}{}{PID_ROCKET_LAUNCHER@A Rockwell BigBazooka rocket launcher. With the deluxe 3 lb. trigger. Fires AP or Explosive Rockets.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_ALLOYS2 2&PID_ALLOYS 5&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_BLUEPRINT_ROCKET_LAUNCHER 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_ROCKET_LAUNCHER 1@exp 750 script fix_boy@fix_Blueprint}
{102}{}{PID_EL_ROCKET_LAUNCHER@This weapon is designed to launch rockets that emits a strong electrical impulse upon impact effectively electrocuting anyone in its blast radius.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_ALLOYS2 2&PID_ELECTRONIC_PARTS 5&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_BLUEPRINT_EL_ROCKET_LAUNCHER 1@PID_ADVANCED_BENCH 1@PID_EL_ROCKET_LAUNCHER 1@exp 850 script fix_boy@fix_Blueprint}
{103}{}{PID_M203@Four barrel rocket launcher that can load standard issues for JHP / AP rockets aswell as incendinary rockets.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_TECH_GUN_CONTROL 4&PID_TECH_SEMI_TRIGGER 1&PID_TECH_MECH_ENGINE 3&PID_BLUEPRINT_M203 1@PID_MACHINERY_SMALL_GUNS 1@PID_M203 1@exp 75000 script fix_boy@fix_Blueprint}
{104}{}{PID_M60@This relatively light machine gun was prized by militaries around for world for its high rate of fire. This reliable, battlefield-proven design, was used on vehicles and for squad level fire-support.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 7&PID_ALLOYS 7@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_M60 1@exp 350 script fix_boy@fix_Generic}
{105}{}{PID_LIGHT_SUPPORT_WEAPON@This squad-level support weapon has a bullpup design. The bullpup design makes it difficult to use while lying down. Because of this it was remanded to National Guard units. It, however, earned a reputation as a reliable weapon that packs a lot of punch for its size.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_METAL_PARTS2 1&PID_ALLOYS 5&PID_PUMP_PARTS 5&PID_BLUEPRINT_LIGHT_SUPPORT_WEAPON 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 800 script fix_boy@fix_Blueprint}
{106}{}{PID_BOZAR@The ultimate refinement of the sniper's art. Although, somewhat finicky and prone to jamming if not kept scrupulously clean, the big weapon's accuracy more than makes up for its extra maintenance requirements.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_CARBON_POLYMER 1&PID_TECH_SCOPE 1&PID_TECH_MICROCHIPS 6&PID_TECH_GUN_CONTROL 3&PID_BLUEPRINT_BOZAR 1@PID_MACHINERY_SMALL_GUNS 1@PID_BOZAR 1@exp 50000 script fix_boy@fix_Blueprint}
{107}{}{PID_MINIGUN@A Rockwell CZ53 Personal Minigun. A multi-barrelled chaingun firing 5mm ammunition at over 60,000 RPM.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_FIREWOOD 1&PID_PUMP_PARTS 7&PID_ALLOYS 5&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_METAL_PARTS 2@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_MINIGUN 1@exp 1000 script fix_boy@fix_Blueprint}
{108}{}{PID_AVENGER_MINIGUN@Rockwell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_MINIGUN 1&PID_METAL_PARTS2 3&PID_ALLOYS2 2&PID_BLUEPRINT_AVENGER_MINIGUN 1@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_AVENGER_MINIGUN 1@exp 1200 script fix_boy@fix_Blueprint}
{109}{}{PID_VINDICATOR_MINIGUN@The Vindicator throws over 90,000 caseless shells per minute down its six carbon-polymer barrels. As the pinnacle of Teutonic engineering skill, it is the ultimate hand-held weapon.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ABSORBER 2&PID_ROTARY_CHAMBER 1&PID_TECH_DELINER 2&PID_ARM_CARBON 4&PID_BLUEPRINT_VINDICATOR_MINIGUN 1@PID_MACHINERY_SMALL_GUNS 1@PID_VINDICATOR_MINIGUN 1@exp 30000 script fix_boy@fix_Blueprint}
{110}{}{PID_LASER_PISTOL@A Wattz 1000 Laser Pistol. Civilian model, so the wattage is lower than military or police versions. Uses small energy cells.@@SK_REPAIR 50@PID_FIREWOOD 1&PID_ALLOYS 2&PID_ELECTRONIC_PARTS 2&PID_METAL_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LASER_PISTOL 1@exp 280 script fix_boy@fix_Generic}
{111}{}{PID_MFT_SYSTEM@Improved system of laser weapon targeting, using a magnetic field.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1&SK_REPAIR 100@PID_METAL_PARTS 1&PID_ELECTRONIC_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MFT_SYSTEM 1@exp 80 script fix_boy@fix_Generic}
{112}{}{PID_MAGNETO_LASER_PISTOL@This Wattz 1000 laser pistol has been upgraded with a magnetic field targeting system that tightens the laser emission, giving this pistol extra penetrating power.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_LASER_PISTOL 1&PID_METAL_PARTS 2&PID_FIREWOOD 1&PID_ALLOYS 4&PID_ELECTRONIC_PARTS 3&PID_MFT_SYSTEM 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MAGNETO_LASER_PISTOL 1@exp 350 script fix_boy@fix_Generic}
{113}{}{PID_PLASMA_PISTOL@Glock 86 Plasma Pistol. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a small energy cell.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 1&PID_FIREWOOD 1&PID_ALLOYS 4&PID_ALLOYS2 1&PID_METAL_PARTS2 1&PID_BLUEPRINT_PLASMA_PISTOL 1@PID_ADVANCED_BENCH 1@PID_PLASMA_PISTOL 1@exp 650 script fix_boy@fix_Blueprint}
{114}{}{PID_EXT_CAPACITOR_BATTERY@Energy storage with additional capacity.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_EXT_CAPACITOR_BATTERY 1@exp 300 script fix_boy@fix_Generic}
{115}{}{PID_PLASMA_PISTOL_EXT_CAP@This Glock 86 Plasma Pistol has had its magnetic housing chamber realigned to reduce the drain on its energy cell. Its efficiency has doubled, allowing it to fire more shots before the battery is expended.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_PISTOL 1&PID_EXT_CAPACITOR_BATTERY 1&PID_BLUEPRINT_PLASMA_PISTOL 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 50 script fix_boy@fix_Generic}
{116}{}{PID_YK32_PULSE_PISTOL@The YK32 was never considered a practical weapon due to its inefficient energy usage and bulky design.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 200&SK_REPAIR 175@PID_METAL_PARTS2 3&PID_ELECTRONIC_PARTS 3&PID_PUMP_PARTS 2&PID_ALLOYS 2&PID_BLUEPRINT_YK32_PULSE_PISTOL 1@PID_ADVANCED_BENCH 1@PID_YK32_PULSE_PISTOL 1@exp 1100 script fix_boy@fix_Blueprint}
{117}{}{PID_LASER_RIFLE@A Wattz 2000 Laser Rifle. Uses micro fusion cells for more powerful lasers, and an extended barrel for additional range.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_FIREWOOD 1&PID_ALLOYS2 2&PID_METAL_PARTS 2&PID_ALLOYS 4&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_LASER_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_LASER_RIFLE 1@exp 700 script fix_boy@fix_Blueprint}
{118}{}{PID_LASER_RIFLE_EXT_CAP@This Wattz 2000 laser rifle has had its recharging system upgraded and a special recycling chip installed that reduces the drain on the micro fusion cell by 50%.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_LASER_RIFLE 1&PID_EXT_CAPACITOR_BATTERY 1&PID_BLUEPRINT_LASER_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_LASER_RIFLE_EXT_CAP 1@exp 50 script fix_boy@fix_Generic}
{119}{}{PID_PLASMA_RIFLE@A Winchester Model P94 Plasma Rifle. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by Micro Fusion Cells.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_FIREWOOD 1&PID_METAL_PARTS2 2&PID_ALLOYS2 2&PID_ALLOYS 6&PID_ELECTRONIC_PARTS 5&PID_BLUEPRINT_PLASMA_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_PLASMA_RIFLE 1@exp 1000 script fix_boy@fix_Blueprint}
{120}{}{PID_TURBO_PLASMA_RIFLE@A modified Winchester P94 plasma rifle. The plasma bolt chamber has been hotwired to accelerate the bolt formation process.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_RIFLE 1&PID_ELECTROMAGNETIC 1&PID_PLASMA_PARTS 1&PID_TECH_TRANSFORMATOR 5&PID_TECH_ELE_WIRES 2&PID_BLUEPRINT_TURBO_PLASMA_RIFLE 1@PID_MACHINERY_SMALL_GUNS 1@PID_TURBO_PLASMA_RIFLE 1@exp 30000 script fix_boy@fix_Blueprint}
{121}{}{PID_YK42B_PULSE_RIFLE@The YK42B is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. It is considered a far superior weapon to the YK32 pistol, having a greater charge capacity and range.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTROMAGNETIC 1&PID_PLASMA_ACCELERATOR 1&PID_TECH_CONDEN 3&PID_TECH_TRANSFORMATOR 1&PID_TECH_ELE_WIRES 3&PID_TECH_PLASMA 1&PID_BLUEPRINT_YK42B_PULSE_RIFLE 1@PID_MACHINERY_SMALL_GUNS 1@PID_YK42B_PULSE_RIFLE 1@exp 50000 script fix_boy@fix_Blueprint}
{122}{}{PID_SOLAR_SCORCHER@Without the sun's rays to charge this weapon's capacitors this gun can't light a match. However, in full daylight, the experimental photo-electric cells that power the Scorcher allow it to turn almost anything into a crispy critter.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 175@PID_METAL_PARTS2 4&PID_ALLOYS2 3&PID_PUMP_PARTS 5&PID_BLUEPRINT_SOLAR_SCORCHER 1@PID_ADVANCED_BENCH 1@PID_SOLAR_SCORCHER 1@exp 1200 script fix_boy@fix_Blueprint}
{123}{}{PID_GATLING_LASER@An H&K L30 Gatling Laser. Designed specifically for military use, these were in the prototype stage at the beginning of the War. Multiple barrels allow longer firing before overheating. Powered by Micro Fusion Cells.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 130@PID_MINIGUN 1&PID_ALLOYS2 3&PID_METAL_PARTS2 5&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_GATLING_LASER 1@PID_ADVANCED_BENCH 1@PID_GATLING_LASER 1@exp 1600 script fix_boy@fix_Blueprint}
{124}{}{PID_BRASS_KNUCKLES@Hardened knuckle grip that is actually made out of steel. They protect your hand, and do more damage, in unarmed combat.@@@PID_PUMP_PARTS 4@@PID_BRASS_KNUCKLES 1@exp 20 script fix_boy@fix_Generic}
{125}{}{PID_SPIKED_KNUCKLES@An improved version of the classic Brass Knuckles. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat.@@@PID_METAL_PARTS 3@@PID_SPIKED_KNUCKLES 1@exp 90 script fix_boy@fix_Generic}
{126}{}{PID_POWER_FIST@A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by small energy cells.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_ALLOYS 3&PID_ELECTRONIC_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_POWER_FIST 1@exp 260 script fix_boy@fix_Generic}
{127}{}{PID_POWER_SERVOS@A system for modifying the power-fist.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_POWER_SERVOS 1@exp 500 script fix_boy@fix_Generic}
{128}{}{PID_MEGA_POWER_FIST@A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. This one has upgraded power servos for increased strength. Powered by small energy cells.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_POWER_FIST 1&PID_POWER_SERVOS 1&PID_BLUEPRINT_MEGA_POWER_FIST 1@PID_ADVANCED_BENCH 1@PID_MEGA_POWER_FIST 1@exp 100 script fix_boy@fix_Blueprint}
{129}{}{PID_SHARPENED_POLE@A wood pole sharpened at one end.@@@PID_FIREWOOD 1@@PID_SHARPENED_POLE 1@exp 5 script fix_boy@fix_Generic}
{130}{}{PID_SPEAR@A sharp-bladed cutting and stabbing weapon.@@@PID_PUMP_PARTS 4&PID_SHARPENED_POLE 1&PID_METAL_PARTS 1@@PID_SPEAR 2@exp 50 script fix_boy@fix_Generic}
{131}{}{PID_SHARP_SPEAR@A razor tipped polearm. The shaft is wooden, and the tip is sharpened steel.@@@PID_SPEAR 1&PID_FLINT 1&PID_METAL_PARTS 3@@PID_SHARP_SPEAR 1@exp 100 script fix_boy@fix_Generic}
{132}{}{PID_KNIFE@A sharp-bladed cutting and stabbing weapon.@@@PID_PUMP_PARTS 2&PID_FIREWOOD 1&PID_METAL_PARTS 1@@PID_KNIFE 2@exp 60 script fix_boy@fix_Generic}
{133}{}{PID_COMBAT_KNIFE@A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use!@@@PID_METAL_PARTS 3&PID_FLINT 1&PID_FIREWOOD 1&PID_PUMP_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_COMBAT_KNIFE 1@exp 135 script fix_boy@fix_Generic}
{134}{}{PID_RIPPER@A Ripper(tm) vibroblade. Powered by a small energy cell, the chainblade rips and tears into it's target.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_ALLOYS 2&PID_ELECTRONIC_PARTS 1&PID_BLUEPRINT_RIPPER 1@PID_ADVANCED_BENCH 1@PID_RIPPER 1@exp 300 script fix_boy@fix_Blueprint}
{135}{}{PID_SLEDGEHAMMER@A large hammer with big handle. Very popular with the muscular crowd.@@@PID_FIREWOOD 1&PID_METAL_PARTS 1@@PID_SLEDGEHAMMER 1@exp 50 script fix_boy@fix_Generic}
{136}{}{PID_SUPER_SLEDGE@A Super Sledgehammer, manufactured by the Brotherhood of Steel, using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback.@@@PID_METAL_PARTS2 2&PID_ALLOYS 1&PID_ELECTRONIC_PARTS 1&PID_SLEDGEHAMMER 1&PID_BLUEPRINT_SUPER_SLEDGE 1@PID_ADVANCED_BENCH 1@PID_SUPER_SLEDGE 1@exp 500 script fix_boy@fix_Blueprint}
{137}{}{PID_CATTLE_PROD@A Farmer's Best Friend model cattle prod from Wattz Electronics. Uses small energy cells for power.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_FIREWOOD 1&PID_ELECTRONIC_PARTS 4&PID_ALLOYS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_CATTLE_PROD 1@exp 250 script fix_boy@fix_Generic}
{138}{}{PID_IMP_CAPACITOR_BATTERY@Improved version of plasma storage, enables higher rate of fire.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 3&PID_METAL_PARTS2 1&PID_METAL_PARTS 2&PID_ALLOYS 1@PID_ADVANCED_BENCH 1@PID_IMP_CAPACITOR_BATTERY 1@exp 700 script fix_boy@fix_Generic}
{139}{}{PID_SUPER_CATTLE_PROD@A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_CATTLE_PROD 1&PID_IMP_CAPACITOR_BATTERY 1&PID_BLUEPRINT_SUPER_CATTLE_PROD 1@PID_ADVANCED_BENCH 1@PID_SUPER_CATTLE_PROD 1@exp 150 script fix_boy@fix_Blueprint}
{140}{}{PID_THROWING_KNIFE@A knife, balanced specifically for throwing. Made of titanium, and laser sharpened.@@@PID_METAL_PARTS 4&PID_FIREWOOD 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_THROWING_KNIFE 10@exp 160 script fix_boy@fix_Generic}
{141}{}{PID_MOLOTOV_COCKTAIL@A home-made flammable grenade.@@@PID_ROT_GUT 16&PID_ROPE 1&PID_ADV_SUPERBURN 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MOLOTOV_COCKTAIL 4@exp 320 script fix_boy@fix_Generic}
{142}{}{PID_FRAG_GRENADE@A generic fragmentation grenade. Contains a small amount of high explosives, the container itself forming most of the damaging fragments. Explodes on contact.@PE_PROFESSION_DEMOLITION_EXPERT 1@PE_PROFESSION_DEMOLITION_EXPERT 1@PID_METAL_PARTS 1&PID_GUNPOWDER 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FRAG_GRENADE 10@exp 100 script fix_boy@fix_Generic}
{143}{}{PID_PLASMA_GRENADE@A magnetically sealed plasma delivery unit, with detonating explosives. Creates a blast of superheated plasma on contact.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_METAL_PARTS 1&PID_REFINED_ORE 2&PID_BLUEPRINT_PLASMA_GRENADE 1@PID_ADVANCED_BENCH 1@PID_PLASMA_GRENADE 10@exp 200 script fix_boy@fix_Blueprint}
{144}{}{PID_DYNACORD@This lethal mixture of Dynamite and Cordex combines the best of both, leaving you no other choice than to worship it.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_METAL_PARTS2 1&PID_GUNPOWDER2 8@PID_ADVANCED_BENCH 1@PID_DYNACORD 10@exp 400 script fix_boy@fix_Generic}
{145}{}{PID_PULSE_GRENADE@Doesn't affect biological creatures. Contact fuze.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 175&SK_REPAIR 150@PID_METAL_PARTS 3&PID_ALLOYS 6&PID_METAL_PARTS2 5&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS2 3&PID_TECH_CONDEN 3&PID_TECH_ELE_WIRES 2&PID_BLUEPRINT_PULSE_GRENADE 1@PID_MACHINERY_ENERGY_CELLS 1@PID_PULSE_GRENADE 10@exp 200 script fix_boy@fix_Blueprint}
{146}{}{PID_SHOCK_GRENADE@This grenade emits a strong electrical impulse effectively electrocuting anyone in its blast radius.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 135@PID_METAL_PARTS 2&PID_ALLOYS 2&PID_METAL_PARTS2 1&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 2&PID_BLUEPRINT_SHOCK_GRENADE 1@PID_ADVANCED_BENCH 1@PID_SHOCK_GRENADE 10@exp 700 script fix_boy@fix_Blueprint}
{147}{}{PID_DYNAMITE@A high explosive, consisting of nitroglycerin mixed with the absorbent substance kiselguhr. Includes a timer.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_GUNPOWDER2 6&PID_DETONATOR_PARTS 1&PID_BLUEPRINT_DYNAMITE 1@PID_ADVANCED_BENCH 1@PID_DYNAMITE 1@exp 330 script fix_boy@fix_Blueprint}
{148}{}{PID_PLASTIC_EXPLOSIVES@A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_GUNPOWDER2 12&PID_DETONATOR_PARTS 1&PID_BLUEPRINT_PLASTIC_EXPLOSIVES 1@PID_ADVANCED_BENCH 1@PID_PLASTIC_EXPLOSIVES 1@exp 450 script fix_boy@fix_Blueprint}
{149}{}{PID_ANTIDOTE@A bottle containing a home-brewed antidote for poison. A milky liquid with floating pieces of radscorpion flesh.@PE_PROFESSION_DOCTOR 1@PE_PROFESSION_DOCTOR 1@PID_SCORPION_TAIL 5@@PID_ANTIDOTE 1@exp 150 script fix_boy@fix_Generic}
{150}{}{PID_JET_ANTIDOTE@This antidote cures the addictions and effects of drugs.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_SCIENCE 165@PID_CHEMICALS2 3&PID_BIOGEL_ADV_NEW 2&PID_ANTIDOTE 2&PID_JET 2&PID_BLUEPRINT_JET_ANTIDOTE 1@PID_MED_MACHINE 1@PID_JET_ANTIDOTE 1@exp 1000 script fix_boy@fix_Blueprint}
{151}{}{PID_WEAK_HEALING_POWDER@A weak low-tech healing agent. It's not quite a stimpak, but it'll do.@@@PID_XANDER_ROOT 1@@PID_WEAK_HEALING_POWDER 1@exp 10 script fix_boy@fix_Generic}
{152}{}{PID_HEALING_POWDER@A low-tech healing agent. It's not quite a stimpak, but it'll do.@@@PID_XANDER_ROOT 1&PID_BROC_FLOWER 1@@PID_HEALING_POWDER 1@exp 20 script fix_boy@fix_Generic}
{153}{}{PID_STIMPAK@A healing chem. When injected, the chem provides immediate healing of minor wounds.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 100@PID_HYPODERMIC_NEEDLE 1&PID_BIO_GEL 1&PID_XANDER_ROOT 1&PID_BROC_FLOWER 1&PID_BLUEPRINT_STIMPAK 1@PID_ADVANCED_BENCH 1|PID_MED_MACHINE 1@PID_STIMPAK 1@exp 110 script fix_boy@fix_Blueprint}
{154}{}{PID_SUPER_STIMPAK@An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to powerful nature of the chemicals used.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 140@PID_STIMPAK 1&PID_BIO_GEL 2&PID_CHEMICALS 1&PID_BLUEPRINT_SUPER_STIMPAK 1@PID_MED_MACHINE 1@PID_SUPER_STIMPAK 1@exp 220 script fix_boy@fix_Blueprint}
{155}{}{PID_HYPO@A medical injection instrument of some kind. It looks very high tech. You don't know what it's filled with but it appears to have only one dose left.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS2 5&PID_BIOGEL_ADV_NEW 1&PID_SUPER_STIMPAK 1&PID_BLUEPRINT_PID_HYPO 1@PID_MED_MACHINE 1@PID_HYPO 1@exp 5000 script fix_boy@fix_Blueprint}
{156}{}{PID_RADAWAY@A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 130@PID_CHEMICALS 1&PID_BIO_GEL 1&PID_BROC_FLOWER 2&PID_BLUEPRINT_RADAWAY 1@PID_MED_MACHINE 1@PID_RADAWAY 1@exp 150 script fix_boy@fix_Blueprint}
{157}{}{PID_RAD_X@Anti-radiation chems to be taken before exposure. No known side effects.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 130@PID_CHEMICALS 1&PID_BIO_GEL 3&PID_XANDER_ROOT 2&PID_BLUEPRINT_RADX 1@PID_MED_MACHINE 1@PID_RAD_X 1@exp 300 script fix_boy@fix_Blueprint}
{158}{}{PID_MENTATS@A pillbox of mind-altering chems. Increases memory related functions, and speeds other mental processes. Highly addictive.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 130@PID_MUTATED_FRUIT 6&PID_CHEMICALS 2&PID_BLUEPRINT_MENTATS 1@PID_MED_MACHINE 1@PID_MENTATS 1@exp 160 script fix_boy@fix_Blueprint}
{159}{}{PID_BUFFOUT@Highly advanced steroids. While in effect, they increase strength and reflexes. Very addictive.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_CHEMICALS 2&PID_MEAT_JERKY 5&PID_BLUEPRINT_BUFFOUT 1@PID_MED_MACHINE 1@PID_BUFFOUT 1@exp 350 script fix_boy@fix_Blueprint}
{160}{}{PID_PSYCHO@An unique delivery system filled with strange and unknown chemicals of probably military origin. It is supposed to increase the combat potential of a soldier.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_SUPER_STIMPAK 1&PID_BIO_GEL 1&PID_CHEMICALS 2&PID_BLUEPRINT_PSYCHO 1@PID_MED_MACHINE 1@PID_PSYCHO 1@exp 280 script fix_boy@fix_Blueprint}
{161}{}{PID_JET@Jet is a powerful metamphetamine that stimulates the central nervous system.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_BRAHMINSHIT 1&PID_CHEMICALS 2&PID_EMPTY_JET 1&PID_BLUEPRINT_JET 1@PID_ADVANCED_BENCH 1@PID_JET 1@exp 150 script fix_boy@fix_Blueprint}
{162}{}{PID_GUM@After Burner is a powerful methamphetamine chewing gum that stimulates the central nervous system. The initial euphoric rush rarely lasts more than a few minutes, but during that time, the user is filled with a rush of energy & strength.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_BIO_GEL 5&PID_CHEMICALS 1&PID_BLUEPRINT_GUM 1@PID_ADVANCED_BENCH 1@PID_GUM 1@exp 400 script fix_boy@fix_Blueprint}
{163}{}{PID_MUTIE@A powerful mutagenic compound designed to give the user abilities resembling those of a super mutant. It has very nasty side effects.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_CHEMICALS 2&PID_SCORPION_TAIL 2&PID_BLUEPRINT_MUTIE 1@PID_MED_MACHINE 1@PID_MUTIE 1@exp 200 script fix_boy@fix_Blueprint}
{164}{}{PID_VOODOO@is a tribal concoction, made from the left-over byproducts of various critters. It imbues the user with greater agility and a sense of invincibility.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_WEAK_HEALING_POWDER 1&PID_GECKO_PELT 1&PID_BLUEPRINT_VOODOO 1@PID_MED_MACHINE 1@PID_VOODOO 1@exp 70 script fix_boy@fix_Blueprint}
{165}{}{PID_LIGHTER@A silver butane lighter, in good condition.@@@PID_FLINT 1&PID_PUMP_PARTS 1&PID_METAL_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LIGHTER 1@exp 70 script fix_boy@fix_Generic}
{166}{}{PID_TENT@A tightly packed tent made of brahmin leather.@@@PID_BRAHMIN_HIDE 8&PID_ROPE 1&PID_SHARPENED_POLE 4@@PID_TENT 1@exp 400 script fix_boy@fix_Generic}
{167}{}{PID_LOCK@A lock, quite standard for this environment.@@@PID_FLINT 1&PID_METAL_PARTS 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LOCK 1@exp 150 script fix_boy@fix_Generic}
{168}{}{PID_LOCKPICKS@A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.@@@PID_FLINT 1&PID_PUMP_PARTS 3&PID_METAL_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LOCKPICKS 1@exp 80 script fix_boy@fix_Generic}
{169}{}{PID_EXP_LOCKPICKS@A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks. This set also includes some special tools for more difficult mechanical locking mechanisms.@@SK_LOCKPICK 125@PID_FLINT 1&PID_BRAHMIN_HIDE 1&PID_METAL_PARTS 7@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_EXP_LOCKPICK_SET 1@exp 260 script fix_boy@fix_Generic}
{170}{}{PID_ROPE@A strong, thick line. About 45 feet in length.@@@PID_FIBER 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ROPE 1@exp 5 script fix_boy@fix_Generic}
{171}{}{PID_WATERBAG_EMPTY@This bag can be filled up with water.@@@PID_BRAHMIN_HIDE 1&PID_FIBER 1@@PID_WATERBAG_EMPTY 1@exp 50 script fix_boy@fix_Generic}
{172}{}{PID_RADIO@This hand-held radio doesn't work but it looks as though it's still in pretty good condition.@@SK_REPAIR 100@PID_PUMP_PARTS 5&PID_METAL_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_RADIO 1@exp 50 script fix_boy@fix_Generic}
{173}{}{PID_SHOVEL@This shovel is the property of it's owners. You can't even conceive of a use for it.@@@PID_METAL_PARTS 1&PID_FIREWOOD 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOVEL 1@exp 50 script fix_boy@fix_Generic}
{174}{}{PID_PRIMITIVE_TOOL@This most rudimentary tool does not look very reliable. Still, it can be used to chop wood or to mine ore.@@@PID_FLINT 1@@PID_PRIMITIVE_TOOL 1@exp 15 script fix_boy@fix_Generic}
{175}{}{PID_AXE@Worn hatchet. Its blade is still in good condition.@@@PID_PUMP_PARTS 1&PID_FIREWOOD 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_AXE 1@exp 30 script fix_boy@fix_Generic}
{176}{}{PID_MULTI_TOOL@A tool set, containing various useful tools, including pliers.@@SK_REPAIR 150@PID_FLINT 1&PID_PUMP_PARTS 3&PID_METAL_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MULTI_TOOL 1@exp 50 script fix_boy@fix_Generic}
{177}{}{PID_MOVABLE_AMMO_BOX_L1@A wooden crate used to store ammo.@@@PID_FIREWOOD 20&PID_FIBER 5&PID_METAL_PARTS2 4@@PID_MOVABLE_AMMO_BOX_L1 1@exp 500 script fix_boy@fix_Generic}
{178}{}{PID_MOVABLE_AMMO_BOX_S1@A wooden crate used to store ammo.@@@PID_FIREWOOD 10&PID_FIBER 2&PID_METAL_PARTS2 2@@PID_MOVABLE_AMMO_BOX_S1 1@exp 500 script fix_boy@fix_Generic}
{179}{}{PID_MOVABLE_POOR_BOX@A small box used to collect money for the poor.@@@PID_FIREWOOD 5&PID_FIBER 3@@PID_MOVABLE_POOR_BOX 1@exp 10 script fix_boy@fix_Generic}
{180}{}{PID_MOVABLE_CHEST@A wooden chest.@@SK_REPAIR 50@PID_FIREWOOD 15&PID_FIBER 5@@PID_MOVABLE_CHEST 1@exp 20 script fix_boy@fix_Generic}
{181}{}{PID_MOVABLE_CRATE@A wooden crate.@@SK_REPAIR 50@PID_FIREWOOD 10&PID_FIBER 5@@PID_MOVABLE_CRATE 1@exp 200 script fix_boy@fix_Generic}
{182}{}{PID_MOVABLE_FOOTLOCKER1@Basic footlocker. Holds stuff, sits at foot of bed.@@SK_REPAIR 115@PID_METAL_PARTS2 2&PID_METAL_PARTS 8&PID_PUMP_PARTS 8@@PID_MOVABLE_FOOTLOCKER1 1@exp 500 script fix_boy@fix_Generic}
{183}{}{PID_MOVABLE_LOCKER1@A storage container.@@SK_REPAIR 120@PID_METAL_PARTS2 2&PID_METAL_PARTS 12&PID_PUMP_PARTS 12@@PID_MOVABLE_LOCKER1 1@exp 500 script fix_boy@fix_Generic}
{184}{}{PID_MOVABLE_SAFE@A heavy metal safe.@@SK_REPAIR 120@PID_METAL_PARTS2 15&PID_ALLOYS2 5&PID_METAL_PARTS 10&PID_PUMP_PARTS 5@@PID_MOVABLE_SAFE 1@exp 825 script fix_boy@fix_Generic}
{185}{}{PID_MOVABLE_FRIDGE@A refrigerator.@SK_SCIENCE 75@SK_SCIENCE 115@PID_PUMP_PARTS 10&PID_METAL_PARTS2 6&PID_ELECTRONIC_PARTS 3&PID_MICRO_FUSION_CELL 100@PID_MULTI_TOOL 1@PID_MOVABLE_FRIDGE 1@exp 500 script fix_boy@fix_Generic}
{186}{}{PID_MOTION_SENSOR@A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of few meters using a tuned radar device.@SK_SCIENCE 75@SK_SCIENCE 135@PID_FIBER 3&PID_METAL_PARTS2 6&PID_ELECTRONIC_PARTS 7&PID_MICRO_FUSION_CELL 20&PID_BLUEPRINT_SENSOR 1@PID_ADVANCED_BENCH 1@PID_MOTION_SENSOR 1@exp 2000 script fix_boy@fix_Generic}
{187}{}{PID_POWERED_ARMOR@A self-contained suit of advanced technology armor. Powered by a micro-fusion reactor, with enough fuel to last a hundred years.@@PE_PROFESSION_ARMORER 2@PID_HIFLO 1&PID_PA_FUEL 1&PID_PA_SHELL 1&PID_ARM_POLYMER_ADV 5&PID_BLUEPRINT_POWERED_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_POWERED_ARMOR 1@exp 100000 script fix_boy@fix_Blueprint}
{188}{}{PID_HARDENED_POWER_ARMOR@A suit of T-51b Power Armor. The hardening process has improved the defensive capability of this high-tech armor system.@@PE_PROFESSION_ARMORER 2@PID_POWERED_ARMOR 1&PID_PA_FUEL 1&PID_PA_SHELL 1&PID_SERVOMOTORS 1&PID_ARM_POLYMER_ADV 11&PID_BLUEPRINT_HARDENED_POWER_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_HARDENED_POWER_ARMOR 1@exp 250000 script fix_boy@fix_Blueprint}
{189}{}{PID_ADVANCED_POWER_ARMOR@This powered armor is composed of lightweight metal alloys, reinforced with ceramic castings at key points. The motion-assist servo-motors appear to be high quality models as well.@@PE_PROFESSION_ARMORER 2@PID_ADVANCED_SHELL 2&PID_PA_FUEL 2&PID_ARM_CERAMIC 4&PID_ARM_POLYMER 12&PID_ARM_POLYMER_LASER 10&PID_ARM_POLYCARBONITE 1&PID_ARM_STEEL 6&PID_BLUEPRINT_ADVANCED_POWER_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_ADVANCED_POWER_ARMOR 1@exp 1000000 script fix_boy@fix_Blueprint}
{190}{}{PID_ADVANCED_POWER_ARMOR_MK2@This powered armor appears to be composed of entirely of lightweight ceramic composites rather than the usual combination of metal and ceramic plates. It seems as though it should give even more protection than the standard Advanced Power Armor.@@PE_PROFESSION_ARMORER 2@PID_ADVANCED_SHELL 4&PID_PA_FUEL 4&PID_ADVANCED_POWER_ARMOR 1&PID_ARM_KEVLAR 3&PID_ARM_POLYMER_LASER 21&PID_ARM_CARBON 15&PID_ARM_GORETEX 4&PID_BLUEPRINT_ADVANCED_POWER_ARMOR_MK2 1@PID_MACHINERY_SMALL_GUNS 1@PID_ADVANCED_POWER_ARMOR_MK2 1@exp 2500000 script fix_boy@fix_Blueprint}
{191}{}{PID_ELECTRONIC_LOCKPICKS@A Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices.@@SK_LOCKPICK 200@PID_ELECTRIC_AMPLIFIER 1&PID_TECH_ELE_ENGINE 1&PID_METAL_PARTS 20@PID_ADVANCED_BENCH 1@PID_ELECTRONIC_LOCKPICKS 1@exp 15000 script fix_boy@fix_Generic}
{192}{}{PID_ELEC_LOCKPICK_MKII@This is the second generation Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices. This Mark II version includes updated software and interface tools.@@SK_LOCKPICK 200@PID_ELECTRONIC_LOCKPICKS 1&PID_ELECTRIC_AMPLIFIER 1&PID_ARM_LEATHER_HIDE 1@PID_ADVANCED_BENCH 1@PID_ELEC_LOCKPICK_MKII 1@exp 25000 script fix_boy@fix_Generic}
{193}{}{PID_PLASMA_GATLING@In contrast with the L30 Gatling laser, this model is not only fully automatic and has a larger ammo capacity, but was also mass produced for military use. While they entered service shortly before the war, they quickly became an important part of the arsenal of pre-War factions.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ROTARY_CHAMBER 1&PID_PLASMA_ACCELERATOR 2&PID_TECH_MECH_ENGINE 1&PID_TECH_ELE_WIRES 3&PID_TECH_PLASMA 2&PID_ARM_POLYCARBONITE 1&PID_BLUEPRINT_PLASMA_GATLING 1@PID_MACHINERY_SMALL_GUNS 1@PID_PLASMA_GATLING 1@exp 75000 script fix_boy@fix_Blueprint}
{194}{}{PID_POWER_HELMET@A self-contained suit of advanced technology armor. Powered by a micro-fusion reactor, with enough fuel to last a hundred years.@@PE_PROFESSION_ARMORER 2@PID_ARM_STEEL 3&PID_ARM_CARBON 3&PID_BLUEPRINT_POWER_HELMET 1@PID_MACHINERY_SMALL_GUNS 1@PID_POWER_HELMET 1@exp 50000 script fix_boy@fix_Blueprint}
{195}{}{PID_HARDENED_POWER_HELMET@A suit of T-51b Power Armor. The hardening process has improved the defensive capability of this high-tech armor system.@@PE_PROFESSION_ARMORER 2@PID_POWER_HELMET 1&PID_ARM_GORETEX 4&PID_CARBON_POLYMER 2&PID_BLUEPRINT_HARDENED_POWER_HELMET 1@PID_MACHINERY_SMALL_GUNS 1@PID_HARDENED_POWER_HELMET 1@exp 100000 script fix_boy@fix_Blueprint}
{196}{}{PID_APA_HELMET@This powered armor is composed of lightweight metal alloys, reinforced with ceramic castings at key points. The motion-assist servo-motors appear to be high quality models as well.@@PE_PROFESSION_ARMORER 2@PID_ARM_CERAMIC 4&PID_ARM_POLYMER 2&PID_BLUEPRINT_ADVANCED_POWER_HELMET 1@PID_MACHINERY_SMALL_GUNS 1@PID_APA_HELMET 1@exp 100000 script fix_boy@fix_Blueprint}
{197}{}{PID_APA_HELMET_MK2@This powered armor is composed of lightweight metal alloys, reinforced with ceramic castings at key points. The motion-assist servo-motors appear to be high quality models as well.@@PE_PROFESSION_ARMORER 2@PID_ARM_GORETEX 7&PID_ARM_CARBON 5&PID_APA_HELMET 1&PID_BLUEPRINT_ADVANCED_POWER_HELMET_MK2 1@PID_MACHINERY_SMALL_GUNS 1@PID_APA_HELMET_MK2 1@exp 200000 script fix_boy@fix_Blueprint}
{198}{}{PID_WAKIZASHI_BLADE@A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use!@@@PID_FLINT 1&PID_FIREWOOD 1&PID_METAL_PARTS2 3@PID_ADVANCED_BENCH 1@PID_WAKIZASHI_BLADE 1@exp 900 script fix_boy@fix_Generic}
{199}{}{PID_PLASMA_SMG@A Wattz Electronics plasma weapon prototype@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 3&PID_FIREWOOD 1&PID_ALLOYS2 4&PID_BLUEPRINT_PLASMA_SMG 1@PID_ADVANCED_BENCH 1@PID_PLASMA_SMG 1@exp 900 script fix_boy@fix_Generic}
{200}{}{PID_LASER_SPEAR@This is a laser emitter attached to razor sharp spear, a combination of tradition and modern technologies. It operates by oscillating a energy beam directly in front of the blade.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 2&PID_SHARP_SPEAR 1&PID_FIBER 1&PID_BLUEPRINT_LASER_SPEAR 1@PID_ADVANCED_BENCH 1@PID_LASER_SPEAR 1@exp 110 script fix_boy@fix_Generic}
{201}{}{PID_RAD_ROCKET@Upon detonation this rocket emits a strong pulse of harmful, ionizing radiation.@@@PID_REFINED_ORE 2&PID_GUNPOWDER2 5@PID_ADVANCED_BENCH 1@PID_RAD_ROCKET 10@exp 300 script fix_boy@fix_Generic}
{202}{}{PID_SNEAK_ARMOR@@@PE_PROFESSION_ARMORER 2@PID_ARM_POLYMER 2&PID_ARM_POLYMER_ADV 2&PID_HIFLO 1&PID_ARM_GORETEX 1&PID_BLUEPRINT_SNEAK_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_SNEAK_ARMOR 1@exp 500000 script fix_boy@fix_Blueprint}
{203}{}{PID_AK47@@@PE_PROFESSION_GUNSMITH_S 2@PID_CYLINDRICAL_LOCK 2&PID_TECH_SEMI_TRIGGER 1&PID_TECH_MICROCHIPS 1&PID_ARM_KEVLAR 1&PID_BLUEPRINT_AK47 1@PID_MACHINERY_SMALL_GUNS 1@PID_AK47 1@exp 500000 script fix_boy@fix_Blueprint}
{204}{}{PID_MEGA_SLEDGE@@@PE_PROFESSION_ENERGY_EXPERT 2@PID_ARM_KEVLAR 2&PID_CARBON_POLYMER 1&PID_SERVOMOTORS 2&PID_BLUEPRINT_MEGA_SLEDGE 1@PID_MACHINERY_SMALL_GUNS 1@PID_MEGA_SLEDGE 1@exp 500000 script fix_boy@fix_Blueprint}
{205}{}{PID_MFC_MK2@@@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_ACCELERATOR 1&PID_TECH_ELE_ENGINE 1&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_EFC 1@PID_MACHINERY_SMALL_GUNS 1@PID_MFC_MK2 100@exp 15000 script fix_boy@fix_Blueprint}
{206}{}{PID_HN_HEAL_NEEDLER_CARTRIDGE@@@PE_PROFESSION_DOCTOR 2@PID_BIOGEL_ADV_NEW 1&PID_CHEMICALS2 1&PID_GUNPOWDER2 3&PID_BLUEPRINT_HEALING_NEEDLER_AMMO 1@PID_MACHINERY_SMALL_GUNS 1@PID_HN_HEAL_NEEDLER_CARTRIDGE 100@exp 15000 script fix_boy@fix_Blueprint}
{207}{}{PID_MINE@@@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_MINE_PART 1&PID_DETONATOR_PARTS 1&PID_GUNPOWDER3 1@PID_ADVANCED_BENCH 1@PID_MINE 1@exp 15000 script fix_boy@fix_Blueprint}
{208}{}{PID_T4_TOOL_KIT@@@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_ELECTRIC_AMPLIFIER 1&PID_CYLINDRICAL_LOCK 1&PID_ROTARY_CHAMBER 1@PID_ADVANCED_BENCH 1@PID_T4_TOOL_KIT 1@exp 45000 script fix_boy@fix_Blueprint}
{209}{}{PID_STEALTH_BOY@@@PE_PROFESSION_ENERGY_EXPERT 2@PID_MOTION_SENSOR 1&PID_ALLOYS2 12&PID_ALLOYS 12@PID_ADVANCED_BENCH 1@PID_STEALTH_BOY 1@exp 5000 script fix_boy@fix_Blueprint}
{210}{}{PID_UPGRATE_PARTS_MK2@@@@PID_UPGRATE_PARTS 10@PID_ADVANCED_BENCH 1@PID_UPGRATE_PARTS_MK2 1@exp 10 script fix_boy@fix_Blueprint}
{211}{}{PID_UPGRATE_PARTS_MK3@@@@PID_UPGRATE_PARTS_MK2 10@PID_ADVANCED_BENCH 1@PID_UPGRATE_PARTS_MK3 1@exp 100 script fix_boy@fix_Blueprint}
